#ifndef YAPT_RENDERER_COMMONDEFINES_H
#define YAPT_RENDERER_COMMONDEFINES_H

#include <Common/Common.h>

#ifdef RENDERER_MODULE
#define RENDERER_MODULE_INTERFACE DLL_EXPORT
#else
#define RENDERER_MODULE_INTERFACE DLL_IMPORT
#endif


#endif