

#ifdef CAMERA_RAYS_STAGE
RWTexture2D<float4> g_outputColor : register(u5, space3);
#elif LIGHT_RAYS_STAGE
#define WRITABLE_LIGHT_DATA
#elif SORT_LIGHT_VERTICES_STAGE
#define WRITABLE_LIGHT_DATA
#endif

static uint g_spectralSampleOffset;

#define RTCR_SPECTRAL_SAMPLESET_EXTRA_OFFSET g_spectralSampleOffset

#include "BDPTCommon.hlsl"



//#define LIGHT_RAYS_STAGE //DONT FORGET TO REMOVE/DISABLE
#ifdef LIGHT_RAYS_STAGE

[numthreads(64, 1, 1)]
void traceLightRays( uint3 groupId : SV_GroupID,
    uint3 groupThreadId : SV_GroupThreadID,
    uint3 dispatchThreadId : SV_DispatchThreadID,
    uint groupIndex : SV_GroupIndex )
{

	g_spectralSampleOffset = 0;

	uint sampleIndex = g_currentRandomSampleIndex + dispatchThreadId.y * g_lightPathsPerDim.x + dispatchThreadId.x;

	SpectralSamples throughPut;
	float3 lightPos;
	float3 lightDir;
	float lightSamplePDF;

	//sample light
	{
		float4 randomSamples0 = getRandomSampleFloat4(sampleIndex, 0);
		float4 randomSamples1 = getRandomSampleFloat4(sampleIndex, 1);

		sampleLightOrEnv(randomSamples1.w, randomSamples0, 0.5f, throughPut, lightPos, lightDir, lightSamplePDF);
	}


	if(throughPut.allSamplesEqual(0.f)) return;

	BDPTRayState rayState;
	rayState.absorption.set(0);
    rayState.setStateFlags(0);
    rayState.numberVolumesEntered = 0;

    float pdfSumRatio = 1;
	uint lastVertexOffset = INVALID_LIGHT_NODE_INDEX;
	uint lightNodeCount = 0;
	float3 rayDir = lightDir;
	float3 rayOrigin = lightPos;
	
	for(uint i = 1; i < g_maxVerticesPerLightPath; ++i)
	{
		float4 randomSamples0 = getRandomSampleFloat4(sampleIndex + i, 0);

		uint rayFlags = RAY_FLAG_NONE;
		uint InstanceInclusionMask = ~0;

		RayQuery<RAY_FLAG_NONE> q;

		RayDesc ray;
		ray.Origin = rayOrigin;
		ray.Direction = rayDir;
		ray.TMin = DEFAULT_RAY_MIN_T;
		ray.TMax = 1000.0;

		q.TraceRayInline(
		    g_accelerationStructure,
		    rayFlags, 
		    InstanceInclusionMask,
		    ray);

		while(q.Proceed());

		if(q.CommittedStatus() == COMMITTED_TRIANGLE_HIT)
		{
			
            SurfaceDefinition surfaceDef;
            PrecalculatedSurfaceData precalculatedSurfaceData;
            float samplingProbabilities[LAYER_COUNT];
            bool triangleHitFrontFace = q.CommittedTriangleFrontFace();
            float3 woOS = -q.CommittedObjectRayDirection();
            uint instId = q.CommittedInstanceID();
            uint primIndex = q.CommittedPrimitiveIndex();
            float2 bary = q.CommittedTriangleBarycentrics();
			
			
            calculateCommonSurfaceParams(rayState, instId, primIndex, bary, woOS, triangleHitFrontFace, randomSamples0.xy,
            surfaceDef, precalculatedSurfaceData, samplingProbabilities);

            float3 wiOS = getSampleDirectionOS(surfaceDef, precalculatedSurfaceData, randomSamples0.w, randomSamples0.xy, samplingProbabilities);

            float3x3 transformNormal = (float3x3)q.CandidateWorldToObject3x4();
            transformNormal = transpose(transformNormal);
			
            float3 normalWS = mul(transformNormal, surfaceDef.geometryNormal);
            float3 posWS = q.WorldRayOrigin() + q.WorldRayDirection() * q.CommittedRayT();
			
			//TODO: store some of the ray state (dispersion,volumes(?))
            LightPathNode pathNode;
            pathNode.instancePrimitiveBarycentrics = float4(asfloat(q.CommittedInstanceID()), asfloat(q.CommittedInstanceID()), bary.x, bary.y);
            pathNode.normalWSNextIndex = float4(normalWS, asfloat(lastVertexOffset));
            pathNode.throughput = throughPut.toFloat4();
            pathNode.positionWSMISSum = float4(posWS, pdfSumRatio);
			//store vertex
			{
				uint vOffset, vCount;
				reserveLightPathNodeSpace(1, vOffset, vCount);
				if(vCount == 0) break;

				storeLightPathVertex(vOffset, pathNode);
				lastVertexOffset = vOffset;
				++lightNodeCount;
			}
			
            if (isZero(wiOS))
            {
                break;
            }

            SpectralSamples w;
            float pdfForward;
            float pdfBackward;
            evaluateSurfaceAndPDFs(surfaceDef, precalculatedSurfaceData, samplingProbabilities, rayState, woOS, wiOS, triangleHitFrontFace, w, pdfForward, pdfBackward);

			if(pdfForward == 0 || pdfBackward == 0)
			{
				break;
			}

            float areaMultiplier = areaDensityMultiplier(posWS - q.WorldRayOrigin(), normalWS);
			
            pdfForward *= areaMultiplier;
            pdfBackward *= areaMultiplier;
			
            pdfSumRatio *= pdfForward / pdfBackward;
            throughPut = throughPut * w / pdfForward;

			rayDir = mul(transformNormal, wiOS);
			rayOrigin = posWS;
        }
		else 
		{
		    break;
		}
	}
	
	if(lightNodeCount > 0)
	{
		LightPathHeader header;
		header.offsetAndCount = uint2(lastVertexOffset, lightNodeCount);
		uint headerOffset = reserveLightPathHeader();
		storeLightPathHeader(headerOffset, header);
	}

}

#endif

#ifdef SORT_LIGHT_VERTICES_STAGE
StructuredBuffer<LightPathNode> g_lightPathVerticesUnsorted : register(t5, space3);

[numthreads(64, 1, 1)]
void sortLightVertices( uint3 groupId : SV_GroupID,
    uint3 groupThreadId : SV_GroupThreadID,
    uint3 dispatchThreadId : SV_DispatchThreadID,
    uint groupIndex : SV_GroupIndex )
{
	uint headerCount = getLightPathsCount();
	if(dispatchThreadId.x >= headerCount) return;

	LightPathHeader header = getLightPathHeader(dispatchThreadId.x);
	uint vCount = header.offsetAndCount.y;
	if(vCount == 0) return;
	//sort
	{
		//allocate space
		uint vOffset;
		reserveLightPathNodeSpaceForSorting(vCount, vOffset);
		//fetch tail		
		LightPathNode lastNode = g_lightPathVerticesUnsorted[header.offsetAndCount.x];
		storeLightPathVertex(vOffset, lastNode);

		//store modified header
		header.offsetAndCount.x = vOffset;
		storeLightPathHeader(dispatchThreadId.x, header);

		//copy entries to linearly
		uint nextIndex = asuint(lastNode.normalWSNextIndex.w);
		for(uint i = 1; i < vCount; ++i)
		{
			LightPathNode node = g_lightPathVerticesUnsorted[nextIndex];
			storeLightPathVertex(vOffset + i, node);
			nextIndex = asuint(node.normalWSNextIndex.w);
		}
	}

}
#endif



#ifdef CAMERA_RAYS_STAGE



groupshared ExtractedLightPathNodeData g_localNodes[MAX_LIGHT_PATH_VERTICES_HARD_LIMIT];
groupshared LightPathHeader g_lightPathHeader;

SpectralSamples ToSpectralSamples(float3 color)
{
	SpectralSamples s;
	s.setFromRGBUnbounded(color);
	return s;
}

[numthreads(8, 8, 1)]
void traceCameraRays( uint3 groupId : SV_GroupID,
    uint3 groupThreadId : SV_GroupThreadID,
    uint3 dispatchThreadId : SV_DispatchThreadID,
    uint groupIndex : SV_GroupIndex )
{
	if(groupIndex == 0)
    {
        uint headerCount = getLightPathsCount();
        uint headerIndex = groupId.y * g_lightPathsPerDim.x + groupId.x;
        headerIndex = headerIndex % headerCount;
        g_lightPathHeader = getLightPathHeader(headerIndex);

    }
	
    GroupMemoryBarrierWithGroupSync();

    if (groupIndex < g_lightPathHeader.offsetAndCount.y)
    {
        LightPathNode node = getLightPathVertex(g_lightPathHeader.offsetAndCount.x + groupIndex);
        g_localNodes[groupIndex] = getExtractedLightPathNodeData(node);
    }
	
    GroupMemoryBarrierWithGroupSync();
	
	g_spectralSampleOffset = 0;

	float2 uv = (float2)dispatchThreadId.xy * g_targetTexDimensions.zw;
    float3 rayDir = generateRayDirection(uv + g_rayDirUvOffset);
	float3 rayOrigin = g_cameraPosition;
	
	SpectralSamples throughput;
	SpectralSamples totalLight;
	throughput.set(1);
	totalLight.set(0);

	BDPTRayState rayState;
	rayState.absorption.set(0);
    rayState.setStateFlags(0);
    rayState.numberVolumesEntered = 0;

    float pdfSumRatio = 1;
	uint cameraVertexCount = 0;
	uint rayIndex = dispatchThreadId.y * g_targetTexDimensions.x + dispatchThreadId.x;
	

	for(uint camVertexIndex = 0; camVertexIndex < g_maxCameraPathVertices; ++camVertexIndex)
	{
		uint sampleIndex = g_currentRandomSampleIndex + (dispatchThreadId.y * 7) + camVertexIndex * 5 + rayIndex * 11;
		float4 randomSamples0 = getRandomSampleFloat4(sampleIndex, 0);

		uint rayFlags = RAY_FLAG_NONE;
		uint InstanceInclusionMask = ~0;

		RayQuery<RAY_FLAG_NONE> q;

		RayDesc ray;
		ray.Origin = rayOrigin;
		ray.Direction = rayDir;
        ray.TMin = DEFAULT_RAY_MIN_T;
		ray.TMax = 1000.0;

		q.TraceRayInline(
		    g_accelerationStructure,
		    rayFlags, 
		    InstanceInclusionMask,
		    ray);

		while(q.Proceed());

		if(q.CommittedStatus() == COMMITTED_TRIANGLE_HIT)
		{
			
            SurfaceDefinition surfaceDef;
            PrecalculatedSurfaceData precalculatedSurfaceData;
            float samplingProbabilities[LAYER_COUNT];
            bool triangleHitFrontFace = q.CommittedTriangleFrontFace();
            float3 woOS = -q.CommittedObjectRayDirection();
            uint instId = q.CommittedInstanceID();
            uint primIndex = q.CommittedPrimitiveIndex();
            float2 bary = q.CommittedTriangleBarycentrics();
			
			
            calculateCommonSurfaceParams(rayState, instId, primIndex, bary, woOS, triangleHitFrontFace, randomSamples0.xy,
            surfaceDef, precalculatedSurfaceData, samplingProbabilities);
			
            float3x3 transformNormal = (float3x3) q.CandidateWorldToObject3x4();
            transformNormal = transpose(transformNormal);
            float3 normalWS = mul(transformNormal, surfaceDef.geometryNormal);
            float3 posWS = q.WorldRayOrigin() + q.WorldRayDirection() * q.CommittedRayT();
			
            if (!surfaceDef.emissive.allSamplesEqual(0))
            {
                totalLight = totalLight + throughput * surfaceDef.emissive; //TODO: proper MIS weight
                break; 
            } 
			else
			//try to connect path to light nodes
			{
                for (uint lightNodeIndex = 0; lightNodeIndex < g_lightPathHeader.offsetAndCount.y; ++lightNodeIndex)
                {
                    LightPathNode lightNode = g_localNodes[lightNodeIndex].node;
                    float3x3 toLocalFrameDir = (float3x3) q.CandidateWorldToObject3x4();
                    float3 toLightWS = lightNode.positionWSMISSum.xyz - posWS;
                    float3 lightPosOS = mul(toLocalFrameDir, toLightWS);
                    float3 wiOS = normalize(lightPosOS);
					
                    SpectralSamples weightLastCameraNode;
                    float pdfRatioLastCameraNode;
					{
                        float pdfForward;
                        float pdfBackward;
						evaluateSurfaceAndPDFs(surfaceDef, precalculatedSurfaceData, samplingProbabilities, rayState, woOS, wiOS, triangleHitFrontFace, weightLastCameraNode, pdfForward, pdfBackward);
					
						if (pdfForward == 0 || pdfBackward == 0 || weightLastCameraNode.allSamplesEqual(0))
                        {
                            continue;
                        }
						
						weightLastCameraNode = weightLastCameraNode / pdfForward;
                        pdfRatioLastCameraNode = pdfForward / pdfBackward;

                    }
                    
					
					//trace visibility ray
					
					//if visible, evaluate the light node surface

                }
				//TODO
			}

            float3 wiOS = getSampleDirectionOS(surfaceDef, precalculatedSurfaceData, randomSamples0.w, randomSamples0.xy, samplingProbabilities);

           

		
            if (isZero(wiOS))
            {
                break;
            }
                
            SpectralSamples w;
            float pdfForward;
            float pdfBackward;
            evaluateSurfaceAndPDFs(surfaceDef, precalculatedSurfaceData, samplingProbabilities, rayState, woOS, wiOS, triangleHitFrontFace, w, pdfForward, pdfBackward);

            //float areaMultiplier = areaDensityMultiplier(posWS - q.WorldRayOrigin(), normalWS);
			
            //pdfForward *= areaMultiplier;
            //pdfBackward *= areaMultiplier;
			
			if(pdfForward == 0 || pdfBackward == 0)
			{
				break;
			}

            pdfSumRatio *= pdfForward / pdfBackward;
            throughput = throughput * w / pdfForward;

			rayDir = mul(transformNormal, wiOS);
			rayOrigin = posWS;
        }
		else 
		{
			float4 skyColor = getSkyBoxColor(rayDir, g_envType, g_envTexIndex);
#ifdef WHITE_FURNACE_TEST
			totalLight = totalLight + throughput * ToSpectralSamples(float3(1,1,1));
#else
			totalLight = totalLight + throughput * ToSpectralSamples(skyColor.xyz);
#endif
			++cameraVertexCount;
		    break;
		}
	}
	
	bool rayDispersed = (rayState.flags & RAYSTATE_FLAGS_SECONDARY_LAMBDAS_TERMINATED) != 0;
    float3 color = totalLight.ToRGB(COLORSPACE_DEFAULT, rayDispersed);

	g_outputColor[dispatchThreadId.xy]  = float4(color, 1.f);
    
	/*
	if(payload.pathLength == 1)
	{
		g_outputColor[dispatchThreadId.xy] = float4(1.0f, 0.0f, 0.0f,  1.f);
	} else if(payload.pathLength < 3)
	{
		g_outputColor[dispatchThreadId.xy] = float4(0.0f, 1.0f, 0.0f, 1.f);
	} else if(payload.pathLength < 6)
	{
		g_outputColor[dispatchThreadId.xy] = float4(0.0f, 0.0f, 1.0f,  10.f);
	} else if(payload.pathLength < 15)
	{
		g_outputColor[dispatchThreadId.xy] = float4(1.0f, 0.0f, 1.0f,  20.f);
	}
	else 
	{
		g_outputColor[dispatchThreadId.xy] = float4(1.0f, 1.0f, 1.0f,  1.f);
	}
	return;
	*/
	
	
	/*
	if(payload.numberVolumesEntered == 0 || payload.rayState == RAY_STATE_CANCELLED)
	{
		g_outputColor[dispatchThreadId.xy] = float4(1.0f, 0.0f, 0.0f,  1.f);
	} else if(payload.numberVolumesEntered < 2)
	{
		g_outputColor[dispatchThreadId.xy] = float4(0.0f, 1.0f, 0.0f, 1.f);
	} else
	{
		g_outputColor[dispatchThreadId.xy] = float4(0.0f, 0.0f, 1.0f,  1.f);
	}
	return;
	*/
	
	/*
	bool resultsValid = !payload.totalLight.hasNan();
	//if the ray was terminated, write out results. if it was cancelled, don't add samples this frame
	if((payload.rayState == RAY_STATE_TERMINATED) && resultsValid) 
	{
		g_outputColor[dispatchThreadId.xy] = color;
	} 
	else
	{
		g_outputColor[dispatchThreadId.xy] = float4(0.0f, 0.0f, 0.0f, 0.0f);
		//g_outputColor[dispatchThreadId.xy] = float4(10.0f, 0.0f, 0.0f, 10.0f); //flag killed samples visually
		//g_outputColor[dispatchThreadId.xy] = float4(payload.totalLight, 10.0f); //flag killed samples visually
	}
	*/
	

}

#endif

