
#ifdef PREPARE_RESOURCES //TODO: move these utilities to simpler setup
RWByteAddressBuffer counters : register(u0, space0);
[numthreads(1, 1, 1)]
void prepareResources( uint3 groupId : SV_GroupID,
    uint3 groupThreadId : SV_GroupThreadID,
    uint3 dispatchThreadId : SV_DispatchThreadID,
    uint groupIndex : SV_GroupIndex )
{
	counters.Store(0, uint3(0, 0, 0));
}

#else

#ifdef CAMERA_RAYS_STAGE
RWTexture2D<float4> g_outputColor : register(u5, space3);
RWTexture2D<uint4> g_MaterialParamsOutput0 : register(u6, space3);
RWTexture2D<uint4> g_MaterialParamsOutput1 : register(u7, space3);

#elif LIGHT_RAYS_STAGE
#define WRITABLE_LIGHT_DATA
#elif SORT_LIGHT_VERTICES_STAGE
#define WRITABLE_LIGHT_DATA
#endif

#include "BDPTCommon.hlsl"

#endif

//#define LIGHT_RAYS_STAGE //DONT FORGET TO REMOVE/DISABLE
#ifdef LIGHT_RAYS_STAGE

[numthreads(64, 1, 1)]
void traceLightRays( uint3 groupId : SV_GroupID,
    uint3 groupThreadId : SV_GroupThreadID,
    uint3 dispatchThreadId : SV_DispatchThreadID,
    uint groupIndex : SV_GroupIndex )
{
	//could potentially remove this check here and just not write path if we can't reserve a header. This way we maybe end up with more valid paths per sample run
	if(g_lightPathsPerDim.x <= dispatchThreadId.x || g_lightPathsPerDim.y <= dispatchThreadId.y) return; 

	SpectralSamples radiance;
	float3 lightPos;
	float3 lightDir;
	
	LightPathNode nodes[2] = {(LightPathNode)0, (LightPathNode)0};
	float pdfForward;

	float3 rayDir;
    float3 rayOrigin;

	
    RandomSampler rand;
    rand.init(g_lightPathRandomDimensionOffset,  dispatchThreadId.y * g_lightPathsPerDim.x + dispatchThreadId.x); //TODO: init properly
	g_spectralMainSampleWavelength = calculateSpectralSampleWavelength(rand.getRandom1());

	//sample light
	{
		float4 randomSamples0 = rand.getRandom4();
		float4 randomSamples1 = rand.getRandom4();
		bool sampledEnvironment;
		float3 lightNormal;
		float lightSamplePDF;
		float lightPosPDF;
		float lightDirPDF;
		uint InstanceID;
		uint primitiveIndex;
        sampleLightOrEnv(randomSamples1.w, randomSamples0, randomSamples1.xy, g_sampleEnvLightProbabilityWeight, radiance, lightPos, lightDir, lightNormal,  lightPosPDF, lightDirPDF, lightSamplePDF, sampledEnvironment, InstanceID, primitiveIndex);

		if (radiance.allSamplesEqual(0.f) || lightPosPDF == 0 || lightDirPDF == 0 || lightSamplePDF == 0)
        return;

		radiance = radiance;

		nodes[0].instanceIndex = InstanceID;
		nodes[0].primitiveIndex = primitiveIndex;
		nodes[0].barycentrics = -1;
		nodes[0].normalWS = lightNormal;
		nodes[0].nextIndex = INVALID_LIGHT_NODE_INDEX;
		nodes[0].radiance = radiance.toFloat4();
		nodes[0].positionWS = lightPos;
		nodes[0].pdfForwardMIS = lightPosPDF * lightSamplePDF;
		nodes[0].flags = sampledEnvironment ? LIGHT_PATH_NODE_FLAG_ENV_LIGHT : 0;
		nodes[0].iorPrevious = IOR_DEFAULT;
		nodes[0].iorCurrent = IOR_DEFAULT;
		pdfForward = lightDirPDF;

		rayDir = lightDir;
		rayOrigin = lightPos + getRaySpawnOffsetUsingNormal(lightNormal, lightDir);

		radiance = radiance * abs(dot(lightNormal, lightDir)) / (lightSamplePDF * lightPosPDF * lightDirPDF);
		
    }

    uint lastVertexOffset = INVALID_LIGHT_NODE_INDEX;
    uint lightNodeCount = 1;
	//reserve header early
    uint headerOffset = reserveLightPathHeader();

	if((g_lightPathsPerDim.y * g_lightPathsPerDim.x) <= headerOffset) return;

	BDPTRayState rayState;
    rayState.setStateFlags(0);
    rayState.numberVolumesEntered = 0;


	for(uint i = 1; i < g_maxVerticesPerLightPath; ++i)
	{
		float4 randomSamples0 = rand.getRandom4();

		uint rayFlags = RAY_FLAG_NONE;
		uint InstanceInclusionMask = ~0;

		RayQuery<RAY_FLAG_NONE> q;

		RayDesc ray;
		ray.Origin = rayOrigin;
		ray.Direction = rayDir;
		ray.TMin = DEFAULT_RAY_MIN_T;
		ray.TMax = DEFAULT_RAY_MAX_T;

		q.TraceRayInline(
		    g_accelerationStructure,
		    rayFlags, 
		    InstanceInclusionMask,
		    ray);

		while(q.Proceed());

		if(q.CommittedStatus() == COMMITTED_TRIANGLE_HIT)
		{
			
			uint currentNodeIndex = i & 0x1;
			uint previousNodeIndex = ((i-1)) & 0x1;

            SurfaceDefinition surfaceDef;
            PrecalculatedSurfaceData precalculatedSurfaceData;
            float samplingProbabilities[LAYER_COUNT];
            bool triangleHitFrontFace = q.CommittedTriangleFrontFace();
            float3 woOS = normalize(-q.CommittedObjectRayDirection());
            uint instId = q.CommittedInstanceID();
            uint primIndex = q.CommittedPrimitiveIndex();
            float2 bary = q.CommittedTriangleBarycentrics();

			uint lightNodeFlags = triangleHitFrontFace ? LIGHT_PATH_NODE_FLAG_HIT_FRONT_FACE : 0;
			lightNodeFlags |= (rayState.getStateFlags() & TRANSMISSION_TYPE_DISPERSED) != 0 ? LIGHT_PATH_NODE_FLAG_TERMINATE_SECONDARY_WAVELENGTHS : 0;
			
            calculateCommonSurfaceParams(rayState, instId, primIndex, bary, woOS, triangleHitFrontFace, surfaceDef, precalculatedSurfaceData, samplingProbabilities);
			
            float3x3 transformNormal = (float3x3)q.CandidateWorldToObject3x4();
            transformNormal = transpose(transformNormal);
			
            float3 normalWS = normalize(mul(transformNormal, surfaceDef.geometryNormal));
            float3 posWS = q.WorldRayOrigin() + q.WorldRayDirection() * q.CommittedRayT();
			
			//TODO: store some of the ray state (dispersion,volumes(?))
			float toAreaDensityForward = solidAngleToAreaDensityMultiplier(posWS - q.WorldRayOrigin(), normalWS);
			
			{
				SpectralSamples abs = rayState.getAbsorption();
				if(!abs.allSamplesEqual(0))
				{
					radiance = radiance * calculateTransmittance(q.CommittedRayT(), abs);
				}
			}


			nodes[currentNodeIndex].instanceIndex = instId;
			nodes[currentNodeIndex].primitiveIndex = primIndex;
			nodes[currentNodeIndex].barycentrics = bary;
			nodes[currentNodeIndex].normalWS = normalWS;
			nodes[currentNodeIndex].radiance = radiance.toFloat4();
			nodes[currentNodeIndex].positionWS = posWS;
			nodes[currentNodeIndex].pdfForwardMIS = pdfForward * toAreaDensityForward;
			nodes[currentNodeIndex].iorPrevious = rayState.getPreviousIOR();
			nodes[currentNodeIndex].iorCurrent = rayState.getCurrentIOR();
			nodes[currentNodeIndex].flags = lightNodeFlags;
			
			bool isDiffuseBounce;
			float3 wiOS = getSampleDirectionOS(surfaceDef, precalculatedSurfaceData, randomSamples0.w, randomSamples0.xy, samplingProbabilities, isDiffuseBounce);
            if (isZero(wiOS))
            {
                break;
            }

            SpectralSamples w;
            float pdfBackward;
            evaluateSurfaceAndPDFs(surfaceDef, precalculatedSurfaceData, samplingProbabilities, rayState, woOS, wiOS, triangleHitFrontFace, true, w, pdfForward, pdfBackward);

			if(pdfBackward == 0)
			{
				break;
			}

			nodes[previousNodeIndex].pdfBackwardMIS = pdfBackward * solidAngleToAreaDensityMultiplier(q.WorldRayOrigin() - posWS, nodes[previousNodeIndex].normalWS.xyz); //TODO: special case for ENV light
			
			//store previous vertex
			{
				uint vOffset, vCount;
				reserveLightPathNodeSpace(1, vOffset, vCount);
				if(vCount == 0) break;

				storeLightPathVertex(vOffset, compressLightPathNode(nodes[previousNodeIndex]));
				lastVertexOffset = vOffset;
				++lightNodeCount;
			}

			nodes[currentNodeIndex].nextIndex = lastVertexOffset;

            radiance = radiance * w * safeDiv(1.f, pdfForward);

			if(radiance.allSamplesEqual(0))
			{
				break;
			}

			rayDir = normalize(mul(transformNormal, wiOS));
			rayOrigin = posWS + getRaySpawnOffsetUsingNormal(normalWS, rayDir);
        }
		else 
		{
		    break;
		}
	}
	
	if(lightNodeCount > 0)
	{
		//store last node
		{
			uint currentNodeIndex = (lightNodeCount-1) & 0x1;
			uint vOffset, vCount;
			reserveLightPathNodeSpace(1, vOffset, vCount);
			if(vCount != 0)
			{
				nodes[currentNodeIndex].nextIndex = lastVertexOffset;
				storeLightPathVertex(vOffset, compressLightPathNode(nodes[currentNodeIndex]));
				lastVertexOffset = vOffset;
			} 
			else
			{
				--lightNodeCount;
			}
		}

		LightPathHeader header;
		header.offsetAndCount = uint2(lastVertexOffset, lightNodeCount);
		header.sampledWavelength = g_spectralMainSampleWavelength;
		storeLightPathHeader(headerOffset, header);
	
	}
	

}

#endif

#ifdef SORT_LIGHT_VERTICES_STAGE
StructuredBuffer<LightPathNodePacked> g_lightPathVerticesUnsorted : register(t5, space3);

[numthreads(64, 1, 1)]
void sortLightVertices( uint3 groupId : SV_GroupID,
    uint3 groupThreadId : SV_GroupThreadID,
    uint3 dispatchThreadId : SV_DispatchThreadID,
    uint groupIndex : SV_GroupIndex )
{
	uint headerCount = getLightPathsCount();
	if(dispatchThreadId.x >= headerCount) return;

	LightPathHeader header = getLightPathHeader(dispatchThreadId.x);
	uint vCount = header.offsetAndCount.y;
	if(vCount == 0) return;

	uint vOffset;
	reserveLightPathNodeSpaceForSorting(vCount, vOffset);
	uint nextIndex = header.offsetAndCount.x;

	for(uint i = 0; i < vCount; ++i)
	{
		LightPathNodePacked node = g_lightPathVerticesUnsorted[nextIndex];
		uint storeIndex = vOffset + vCount - i - 1 ;
		storeLightPathVertex(storeIndex, node);		
		nextIndex = getNextIndexFromPackedNode(node);
	}
	

	//store modified header
	header.offsetAndCount.x = vOffset;
	storeLightPathHeader(dispatchThreadId.x, header);

}
#endif



#ifdef CAMERA_RAYS_STAGE



groupshared ExtractedLightPathNodeData g_localNodes[MAX_LIGHT_PATH_VERTICES_HARD_LIMIT];
groupshared LightPathHeader g_lightPathHeader;

SpectralSamples ToSpectralSamples(float3 color)
{
	SpectralSamples s;
	s.setFromRGBUnbounded(color);
	return s;
}

bool calculateConnectingLightNodeWeightsAndPDFs(LightPathNode lightNode, uint lightNodeIndex, float3 prevVertexPos, float3 nextVertexPos, out float pdfForwardOut, out float pdfBackwardOut, out SpectralSamples weightOut)
{
    if (lightNodeIndex == 0)
    {
        pdfForwardOut = 1;
        pdfBackwardOut = 1;
		
        weightOut.fromFloat4(float4(1, 1, 1, 1));
    }
    else
    {
        float3x4 toLocalFrame = g_localNodes[lightNodeIndex].worldToObjSpace;
        float3 lightPosOS = mul(toLocalFrame, float4(lightNode.positionWS.xyz, 1)).xyz;
        float3 prevLightPosOS = mul(toLocalFrame, float4(prevVertexPos, 1)).xyz;
        float3 camNodePosOS = mul(toLocalFrame, float4(nextVertexPos, 1)).xyz;
        float3 wiOS = normalize(camNodePosOS - lightPosOS);
        float3 woOSLightConnection = normalize(prevLightPosOS - lightPosOS);
        uint lightNodeFlags = asuint(lightNode.flags);
        bool triangleHitFrontFace = (lightNodeFlags & LIGHT_PATH_NODE_FLAG_HIT_FRONT_FACE) != 0;
                            
        SurfaceDefinitionRGB surfaceDefRGB = g_localNodes[lightNodeIndex].surfaceDefRGB;
	    
        SurfaceDefinition surfaceDef = convertSurfaceDefinitionFromRGB(surfaceDefRGB);
        PrecalculatedSurfaceData precalculatedSurfaceData;
        float samplingProbabilities[LAYER_COUNT];
		
		//for now just initialize with node data. maybe needs a better way (update during light node traversal?)
        BDPTRayState rayState;
        rayState.ior[0] = lightNode.iorPrevious;
        rayState.ior[1] = lightNode.iorCurrent;
        rayState.numberVolumesEntered = 2;
        rayState.setStateFlags(0);

        getPrecalculatedSurfaceData(surfaceDef, rayState.getCurrentIOR(), rayState.getPreviousIOR(), woOSLightConnection, triangleHitFrontFace, precalculatedSurfaceData);
        calculateNormalizedMaterialLayerSamplingProbabilities(surfaceDef, precalculatedSurfaceData, samplingProbabilities);
        evaluateSurfaceAndPDFs(surfaceDef, precalculatedSurfaceData, samplingProbabilities, rayState, woOSLightConnection, wiOS, triangleHitFrontFace, true, weightOut, pdfForwardOut, pdfBackwardOut);
					
        if (pdfBackwardOut == 0 || weightOut.allSamplesEqual(0))
        {
            return false;
        }
						
        weightOut = weightOut * safeDiv(1.f, pdfForwardOut);
    }
	
    return true;
}

struct CameraVertexContext
{
    SurfaceDefinition surfaceDef;
    PrecalculatedSurfaceData precalculatedSurfaceData;
    SpectralSamples throughput;
	float samplingProbabilities[LAYER_COUNT];
    float3 posWS;
    float pdfRatioSum;
    float3 normalWS;
    float3 woOS;
    float3 wiOS;
	
    float3 prevNodePosWS;
    float previousPDFForwardMIS;
    float3 prevNodeNormalWS;
    float currentNodeForwardPDFMIS;
    bool triangleHitFrontFace;
};

struct LightVertexContext
{
    float3 prevNodePosWS;
    float previousPDFForwardMIS;
    float3 prevNodeNormalWS;
    uint originatingNodeFlags;
	float riSum;
};

float calculateMISWeight( uint cameraVertexIndex, in CameraVertexContext camVertex,
uint lightVertexIndex, in LightVertexContext lightVertex, in LightPathNode lightNode,
float pdfBackwardLastCameraNode, float pdfForwardLastCameraNode, float pdfBackwardLastLightNode, float pdfForwardLastLightNode)
{
    float riSumCam = camVertex.pdfRatioSum;
	//TODO: the actual first node would be the origina of the ray from camera but its not considered (and can never be hit by path from light). Revisit if its correct to just ignore it here
    if (cameraVertexIndex > 1)
    {
        float pdfBackwardPrevNodeCam = pdfBackwardLastCameraNode * solidAngleToAreaDensityMultiplier(camVertex.prevNodePosWS - camVertex.posWS, camVertex.prevNodeNormalWS);
        float ratioPrevCam = safeDiv(pdfBackwardPrevNodeCam, camVertex.previousPDFForwardMIS);
        riSumCam = ratioPrevCam * riSumCam + ratioPrevCam;
    }
    if (cameraVertexIndex > 0)
    {
        float ratioLastCamNode = safeDiv(pdfForwardLastLightNode * solidAngleToAreaDensityMultiplier(camVertex.posWS - lightNode.positionWS.xyz, camVertex.normalWS), camVertex.currentNodeForwardPDFMIS);
        riSumCam = ratioLastCamNode * riSumCam + ratioLastCamNode;
    }

	
    float riSumLight = lightVertex.riSum;
    if (lightVertexIndex == 0)
    {
        bool isEnvLight = (lightNode.flags & LIGHT_PATH_NODE_FLAG_ENV_LIGHT) != 0;
        float lightPickPDF;
        float lightPosPDF;
        float lightDirPDF;
		
        float3 camToLight = lightNode.positionWS.xyz - camVertex.posWS;
        float camToLightLength = length(camToLight);
        float3 lightToCam = camToLight / camToLightLength;
		
        float misWeightToLight;
        if (isEnvLight)
        {
            pdfForSamplingEnv(g_sampleEnvLightProbabilityWeight, lightToCam, lightPickPDF, lightPosPDF, lightDirPDF);
            misWeightToLight = pdfForwardLastCameraNode;
        }
        else
        {
            pdfForSamplingLightNode(lightNode, lightToCam, g_sampleEnvLightProbabilityWeight, lightPickPDF, lightPosPDF, lightDirPDF);
            misWeightToLight = pdfForwardLastCameraNode * solidAngleToAreaDensityMultiplier(camToLight, lightNode.normalWS);
        }
		
        riSumLight = safeDiv(pdfForwardLastCameraNode, (lightPickPDF * lightPosPDF));
		
    } else
    {
        float pdfBackwardPrevNodeLight = pdfBackwardLastLightNode;
        if (lightVertexIndex == 1)
        {
            bool isEnvLight = (lightVertex.originatingNodeFlags & LIGHT_PATH_NODE_FLAG_ENV_LIGHT) != 0;
            if(!isEnvLight)
            {
                pdfBackwardPrevNodeLight *= solidAngleToAreaDensityMultiplier(lightVertex.prevNodePosWS - lightNode.positionWS, lightVertex.prevNodeNormalWS);
            }
        }
		
         
        float ratioPrevLightNode = safeDiv(pdfBackwardPrevNodeLight, lightVertex.previousPDFForwardMIS);
        riSumLight = ratioPrevLightNode * riSumLight + ratioPrevLightNode;

		float ratioLastLightNode = safeDiv(pdfForwardLastCameraNode * solidAngleToAreaDensityMultiplier(lightNode.positionWS.xyz - camVertex.posWS, lightNode.normalWS), lightNode.pdfForwardMIS);
		riSumLight = ratioLastLightNode * riSumLight + ratioLastLightNode;
    }
	
    float misWeight = 1.f / (1 + riSumCam + riSumLight);
	
    return misWeight;
}

float calculateMISWeightOnCameraPathHittingLight(uint cameraVertexIndex, uint instanceIndex, uint primitiveIndex, float2 bary, CameraVertexContext camVertexContext)
{
	//if we hit directly to light from camera, this path can only be done this way and MIS is 1
	if (cameraVertexIndex == 0)
	{
		return 1.f;
	}

    float lightPickPDF;
    float lightPosPDF;
    float lightDirPDF;
	
    float3 towardsPreviousCameraNode = camVertexContext.prevNodePosWS - camVertexContext.posWS;
	float3 towardsPreviousCameraNodeDir = normalize(towardsPreviousCameraNode);
    pdfForSamplingLight(instanceIndex, primitiveIndex, bary, camVertexContext.normalWS, towardsPreviousCameraNodeDir, g_sampleEnvLightProbabilityWeight, lightPickPDF, lightPosPDF, lightDirPDF);
	
    float riSumCam = camVertexContext.pdfRatioSum;
    float ratioAtLight = safeDiv(lightPickPDF * lightPosPDF, camVertexContext.currentNodeForwardPDFMIS);
    float ratioBeforeLight = safeDiv(lightDirPDF * solidAngleToAreaDensityMultiplier(towardsPreviousCameraNode, camVertexContext.prevNodeNormalWS), camVertexContext.previousPDFForwardMIS);

    riSumCam = ratioBeforeLight * riSumCam + ratioBeforeLight;
    riSumCam = ratioAtLight * riSumCam + ratioAtLight;

    float misWeight = 1.f / (1 + riSumCam);
    return misWeight;
}

float calculateMISWeightOnCameraPathMissing(uint cameraVertexIndex, CameraVertexContext context, float3 rayOrigin, float3 rayDir)
{
	//if we hit directly to light from camera, this path can only be done this way and MIS is 1
    if (cameraVertexIndex == 0)
    {
        return 1.f;
    }

    float lightPickPDF;
	float lightPosPDF;
	float lightDirPDF;

	pdfForSamplingEnv(g_sampleEnvLightProbabilityWeight, -rayDir, lightPickPDF, lightPosPDF, lightDirPDF);

	float riSumCam = context.pdfRatioSum;
    float ratioAtLight = (lightPickPDF * lightPosPDF) / context.currentNodeForwardPDFMIS;
    float ratioBeforeLight = lightDirPDF / context.previousPDFForwardMIS; //this hits a surface. Should it have solidAngleToAreaDensityMultiplier with distance being world bounds or smth?

    riSumCam = ratioBeforeLight * riSumCam + ratioBeforeLight;
    riSumCam = ratioAtLight * riSumCam + ratioAtLight;

	float misWeight = 1.f / (1 + riSumCam);
    return misWeight;
	
}


SpectralSamples calculateLightPathRadiance(uint cameraVertexIndex, in CameraVertexContext camVertex,
uint lightVertexIndex, in LightVertexContext lightVertex, in BDPTRayState rayState)
{
    SpectralSamples retVal;
    retVal.set(0);
	
    uint lightNodeIndex = lightVertexIndex;
    LightPathNode lightNode = g_localNodes[lightNodeIndex].node;
                    
    SpectralSamples weightLastCameraNode;
    float pdfForwardLastCameraNode;
    float pdfBackwardLastCameraNode;
	//evaluate weight PDFs for connecting camera node
	{
						
        float pdfForward;
        float pdfBackward;
        evaluateSurfaceAndPDFs(camVertex.surfaceDef, camVertex.precalculatedSurfaceData, camVertex.samplingProbabilities, rayState, camVertex.woOS, camVertex.wiOS, camVertex.triangleHitFrontFace, false, weightLastCameraNode, pdfForward, pdfBackward);
					
        if (pdfForward == 0 || weightLastCameraNode.allSamplesEqual(0) )
        {
            return retVal;
        }
						
        weightLastCameraNode = weightLastCameraNode / pdfForward;

        pdfForwardLastCameraNode = pdfForward;
        pdfBackwardLastCameraNode = pdfBackward;
    }
					
    SpectralSamples weightLastLightNode = (SpectralSamples)0;
    float pdfForwardLastLightNode;
    float pdfBackwardLastLightNode;
	//evaluate weight PDFs for connecting light node
	{
        bool connectionValid = calculateConnectingLightNodeWeightsAndPDFs(lightNode, lightNodeIndex, lightVertex.prevNodePosWS, camVertex.posWS, pdfForwardLastLightNode, pdfBackwardLastLightNode, weightLastLightNode);
        if (!connectionValid)
        {
            return retVal;
        }

    }


                    
	float3 toLightWS = lightNode.positionWS.xyz - camVertex.posWS;
	float toLightLenSqr = dot(toLightWS, toLightWS);
    float toLightLen = sqrt(toLightLenSqr);
	float3 toLightDir = toLightWS / toLightLen;
	//trace visibility ray to check visibility with node
	{
        const float VISIBILITY_RAY_EPSILON = 0.001f;
        
		
        uint rayFlags = RAY_FLAG_NONE;
        uint InstanceInclusionMask = ~0;
        RayDesc ray;
        ray.Origin = camVertex.posWS + getRaySpawnOffsetTowardsRay(toLightDir);
        ray.Direction = toLightDir;
        ray.TMin = DEFAULT_RAY_MIN_T;
        ray.TMax = DEFAULT_RAY_MIN_T + toLightLen + VISIBILITY_RAY_EPSILON;

        RayQuery < RAY_FLAG_NONE > q;
        q.TraceRayInline(
							g_accelerationStructure,
							rayFlags,
							InstanceInclusionMask,
							ray);

        while (q.Proceed());
						
        bool lightNodeVisible = false;
		bool isEnvLight = (lightNode.flags & LIGHT_PATH_NODE_FLAG_ENV_LIGHT) != 0;
						
        if (q.CommittedStatus() == COMMITTED_TRIANGLE_HIT)
        {
            uint visInstId = q.CommittedInstanceID();
            uint visPrimIndex = q.CommittedPrimitiveIndex();
							
			//if we hit the light node instance and primitive, good enough for now (could check barycentrics to make sure but should be neglible)
            if (visInstId == lightNode.instanceIndex && visPrimIndex == lightNode.primitiveIndex)
            {
                lightNodeVisible = true;
            }

        } 
		else if(isEnvLight)
		{
			lightNodeVisible = true;
		}
						
        if (!lightNodeVisible)
        {
            return retVal;
        }
    }
					
	//can connect, evaluate connection and accumulate total light
	{
        float misWeight = calculateMISWeight(cameraVertexIndex, camVertex, lightVertexIndex, lightVertex, lightNode, pdfBackwardLastCameraNode, pdfForwardLastCameraNode, pdfBackwardLastLightNode, pdfForwardLastLightNode);

        SpectralSamples radianceFromLight;
        radianceFromLight.fromFloat4(lightNode.radiance);
						
        float geometryTerm = 1.f / toLightLenSqr;
		geometryTerm *= abs(dot(camVertex.normalWS, toLightDir));
		if((lightNode.flags & LIGHT_PATH_NODE_FLAG_ENV_LIGHT) == 0)
		{
			geometryTerm *= abs(dot(lightNode.normalWS, toLightDir));
		}

		SpectralSamples absorptionOnConnection = rayState.getAbsorption();
		if(!absorptionOnConnection.allSamplesEqual(0))
		{
            weightLastCameraNode = weightLastCameraNode * calculateTransmittance(toLightLen, absorptionOnConnection);
        }

		
        retVal =  weightLastLightNode * weightLastCameraNode * camVertex.throughput * radianceFromLight  * geometryTerm * misWeight;

        return retVal;
    }
	
}

bool shouldPathContribute(uint cameraNodeIndex, uint lightNodeIndex)
{
	bool skipCameraNode = (cameraNodeIndex < g_effectiveCameraPathNodesRange.x) ||  (cameraNodeIndex > g_effectiveCameraPathNodesRange.y);
	bool skipLightNode = (lightNodeIndex < g_effectiveLightPathNodesRange.x) ||  (lightNodeIndex > g_effectiveLightPathNodesRange.y);

	return !skipCameraNode && !skipLightNode;
}

#define THREAD_GROUP_DIM_SIZE_CAM_RAY 8

uint2 calculateSourceTextureTexelCoordinates(uint2 groupThreadId, uint2 groupIndex)
{
	const uint WORKGROUPS_IN_SWIZZLE = 8;
	
	uint2 blockIndex = (groupIndex / WORKGROUPS_IN_SWIZZLE);
	uint2 workGroupsInSwizzle = min(uint2(WORKGROUPS_IN_SWIZZLE, WORKGROUPS_IN_SWIZZLE), g_cameraRayWorkGroupCount - blockIndex * WORKGROUPS_IN_SWIZZLE);
	uint2 blockOffset = blockIndex * THREAD_GROUP_DIM_SIZE_CAM_RAY * WORKGROUPS_IN_SWIZZLE;	

	//offset workgroup
	uint2 blockGroupIndex = groupIndex - blockOffset;
	uint flatGroupsCount = workGroupsInSwizzle.x * workGroupsInSwizzle.y;
	uint flatGroupIndex = blockGroupIndex.y * workGroupsInSwizzle.x + blockGroupIndex.x;
	flatGroupIndex = (flatGroupIndex + g_cameraWorkGroupOffset) % flatGroupsCount;

	uint2 inBlockGroupOffset = uint2(flatGroupIndex % workGroupsInSwizzle.x, flatGroupIndex / workGroupsInSwizzle.x);
	uint2 threadOffset = groupThreadId * workGroupsInSwizzle;

	return blockOffset + inBlockGroupOffset + threadOffset;
}

[numthreads(THREAD_GROUP_DIM_SIZE_CAM_RAY, THREAD_GROUP_DIM_SIZE_CAM_RAY, 1)]
void traceCameraRays( uint3 groupId : SV_GroupID,
    uint3 groupThreadId : SV_GroupThreadID,
    uint3 dispatchThreadId : SV_DispatchThreadID,
    uint groupIndex : SV_GroupIndex )
{
	uint2 sourceTextureIndices = calculateSourceTextureTexelCoordinates(groupThreadId.xy, groupId.xy);
	uint2 rayIndices = dispatchIndicesToRayIndices(sourceTextureIndices);

	if(rayIndices.x >= g_targetTexDimensions.x || rayIndices.y >= g_targetTexDimensions.y) return;

	RandomSampler rand;
	uint lightPathScrambleOffset = 0;//g_lightPathsPerDim.y * g_lightPathsPerDim.x; //should lightpaths use completely different random values?
    rand.init(0, lightPathScrambleOffset + rayIndices.y * g_targetTexDimensions.x + rayIndices.x); //TODO: init properly


	if(groupIndex == 0)
    {
		uint maxLightPathCount = g_lightPathsPerDim.y * g_lightPathsPerDim.x;
        uint headerCount = min(maxLightPathCount, getLightPathsCount());
		if(headerCount == 0)
		{
			g_lightPathHeader.offsetAndCount = uint2(0, 0);
			g_lightPathHeader.sampledWavelength = calculateSpectralSampleWavelength(rand.getRandom1());
		}
		else
		{
			RandomSampler randTemp;
			randTemp.init(0, groupId.y * g_lightPathsPerDim.x + groupId.x);

			
			uint headerIndex = min(floor(randTemp.getRandom1() * headerCount), headerCount - 1);
			g_lightPathHeader = getLightPathHeader(headerIndex);
		}
        

    }
	
    GroupMemoryBarrierWithGroupSync();
	
	g_spectralMainSampleWavelength = g_lightPathHeader.sampledWavelength;

    if (groupIndex < g_lightPathHeader.offsetAndCount.y)
    {
        LightPathNode node = decompressLightPathNode(getLightPathVertex(g_lightPathHeader.offsetAndCount.x + groupIndex));
        g_localNodes[groupIndex] = getExtractedLightPathNodeData(node);
    }
	
    GroupMemoryBarrierWithGroupSync();
	
	

	float2 uv = (float2)rayIndices * g_targetTexDimensions.zw;
    float3 rayDir = generateRayDirection(uv + g_rayDirUvOffset, rand.getTexelOffset());
	float3 rayOrigin = g_cameraPosition;
	
	SpectralSamples totalLight;
	totalLight.set(0);

	BDPTRayState rayState;
    rayState.setStateFlags(0);
    rayState.numberVolumesEntered = 0;

    CameraVertexContext camVertexContext;
    camVertexContext.throughput.set(1);
    camVertexContext.pdfRatioSum = 0;
    camVertexContext.previousPDFForwardMIS = 0;
	
	float pdfForwardCamera = 1;
	uint camVertexIndex = 0;
	uint pathCount = 0;

	for(; camVertexIndex < g_maxCameraPathVertices; ++camVertexIndex)
	{
		uint rayFlags = RAY_FLAG_NONE;
		uint InstanceInclusionMask = ~0;

		RayQuery<RAY_FLAG_NONE> q;

		RayDesc ray;
		ray.Origin = rayOrigin;
		ray.Direction = rayDir;
        ray.TMin = DEFAULT_RAY_MIN_T;
		ray.TMax = DEFAULT_RAY_MAX_T;

		q.TraceRayInline(
		    g_accelerationStructure,
		    rayFlags, 
		    InstanceInclusionMask,
		    ray);

		while(q.Proceed());

		float4 randomSamples0 = rand.getRandom4();

		if(q.CommittedStatus() == COMMITTED_TRIANGLE_HIT)
		{
			
            camVertexContext.posWS = q.WorldRayOrigin() + q.WorldRayDirection() * q.CommittedRayT();
            camVertexContext.triangleHitFrontFace = q.CommittedTriangleFrontFace();
            camVertexContext.woOS = normalize(-q.CommittedObjectRayDirection());
            uint instId = q.CommittedInstanceID();
            uint primIndex = q.CommittedPrimitiveIndex();
            float2 bary = q.CommittedTriangleBarycentrics();
			
			bool outputShadingParams = firstBounceMaterialWriteEnabled();
			if(camVertexIndex == 0 && outputShadingParams)
			{
				SurfaceDefinitionRGB surfaceDefRGB;
				fillSurfaceDefRGB(instId, primIndex, bary, surfaceDefRGB);
				float3x3 transformNormal = (float3x3) q.CandidateWorldToObject3x4();
				transformNormal = transpose(transformNormal);


				writeMaterialParamsForFirstBounce(sourceTextureIndices.xy, surfaceDefRGB, transformNormal, q.CommittedRayT(), g_MaterialParamsOutput0, g_MaterialParamsOutput1);
				calculateCommonSurfaceParams(rayState, surfaceDefRGB, camVertexContext.woOS, camVertexContext.triangleHitFrontFace, camVertexContext.surfaceDef, camVertexContext.precalculatedSurfaceData, camVertexContext.samplingProbabilities);
			} 
			else
			{
				calculateCommonSurfaceParams(rayState, instId, primIndex, bary, camVertexContext.woOS, camVertexContext.triangleHitFrontFace, camVertexContext.surfaceDef, camVertexContext.precalculatedSurfaceData, camVertexContext.samplingProbabilities);
			}
			
            
			
            float3x3 transformNormal = (float3x3) q.CandidateWorldToObject3x4();
            transformNormal = transpose(transformNormal);
            camVertexContext.normalWS = normalize(mul(transformNormal, camVertexContext.surfaceDef.geometryNormal));
            
			
            camVertexContext.currentNodeForwardPDFMIS = pdfForwardCamera * solidAngleToAreaDensityMultiplier(camVertexContext.posWS - q.WorldRayOrigin(), camVertexContext.normalWS);
			
			{
				SpectralSamples abs = rayState.getAbsorption();
				if(!abs.allSamplesEqual(0))
				{
                    camVertexContext.throughput = camVertexContext.throughput * calculateTransmittance(q.CommittedRayT(), abs);
                }
			}

            if (!camVertexContext.surfaceDef.emissive.allSamplesEqual(0))
            {
                float misWeight = calculateMISWeightOnCameraPathHittingLight(camVertexIndex, instId, primIndex, bary, camVertexContext);
				if(shouldPathContribute(camVertexIndex, 0))
				{
					totalLight = totalLight + camVertexContext.throughput * camVertexContext.surfaceDef.emissive * misWeight;
					++pathCount;
				}
                
                break; 
            } 
			else
			//try to connect path to light nodes
			{
                LightVertexContext lightVertexContext;
				lightVertexContext.riSum = 0;
                for (uint lightVertexIndex = 0; lightVertexIndex < g_lightPathHeader.offsetAndCount.y; ++lightVertexIndex)
                {
                    uint lightNodeIndex = lightVertexIndex;
                    LightPathNode lightNode = g_localNodes[lightNodeIndex].node;
                    
                    float3x4 toLocalFrame = q.CandidateWorldToObject3x4();
                    float3 lightPosOS = mul(toLocalFrame, float4(lightNode.positionWS.xyz, 1)).xyz;
                    float3 posOS = mul(toLocalFrame, float4(camVertexContext.posWS, 1)).xyz;
                    camVertexContext.wiOS = normalize(lightPosOS - posOS);
					
                    SpectralSamples lightConnectionRadiance = calculateLightPathRadiance(camVertexIndex, camVertexContext, lightVertexIndex, lightVertexContext, rayState);
                    
					if(shouldPathContribute(camVertexIndex, lightVertexIndex + 1))
					{
						totalLight = totalLight + lightConnectionRadiance;
						++pathCount;
					}

					float pdfRatio = lightNode.pdfBackwardMIS / lightNode.pdfForwardMIS;
					lightVertexContext.riSum += 1;
					lightVertexContext.riSum *= pdfRatio;
					

                    lightVertexContext.prevNodeNormalWS = lightNode.normalWS;
                    lightVertexContext.prevNodePosWS = lightNode.positionWS;
                    lightVertexContext.previousPDFForwardMIS = lightNode.pdfForwardMIS;
					if(lightVertexIndex == 0)
                    {
                        lightVertexContext.originatingNodeFlags = lightNode.flags;
                    }

                }
				//TODO
			}
			bool isDiffuseBounce;
            float3 wiOS = getSampleDirectionOS(camVertexContext.surfaceDef, camVertexContext.precalculatedSurfaceData, randomSamples0.w, randomSamples0.xy, camVertexContext.samplingProbabilities, isDiffuseBounce);

            if (isZero(wiOS))
            {
                break;
            }
                
			if(isDiffuseBounce)
			{
				rayState.addFlags(RAYSTATE_FLAGS_HAS_DIFFUSE_BOUNCE); 
			}

            SpectralSamples w;
            float pdfForward;
            float pdfBackward;
            evaluateSurfaceAndPDFs(camVertexContext.surfaceDef, camVertexContext.precalculatedSurfaceData, camVertexContext.samplingProbabilities, rayState, camVertexContext.woOS, wiOS, camVertexContext.triangleHitFrontFace, false, w, pdfForward, pdfBackward);

			if(pdfForward == 0)
			{
				break;
			}


			if(camVertexIndex > 0)
            {
                float pdfBackwardPrevNode = pdfBackward * solidAngleToAreaDensityMultiplier(q.WorldRayOrigin() - camVertexContext.posWS, camVertexContext.prevNodeNormalWS);
                float ratio = pdfBackwardPrevNode / camVertexContext.previousPDFForwardMIS;
				camVertexContext.pdfRatioSum += 1;
				camVertexContext.pdfRatioSum *= ratio;

            }
			
            camVertexContext.prevNodeNormalWS = camVertexContext.normalWS;
            camVertexContext.prevNodePosWS = camVertexContext.posWS;
            camVertexContext.previousPDFForwardMIS = camVertexContext.currentNodeForwardPDFMIS;
			pdfForwardCamera = pdfForward;

            camVertexContext.throughput = camVertexContext.throughput * w / pdfForward;

			rayDir = normalize(mul(transformNormal, wiOS));
            rayOrigin = camVertexContext.posWS + getRaySpawnOffsetUsingNormal(camVertexContext.normalWS, rayDir);
        }
		else 
		{

			bool outputShadingParams = firstBounceMaterialWriteEnabled();
			if (outputShadingParams && camVertexIndex == 0)
			{
				writeEmptyMaterialParamsForFirstBounce(sourceTextureIndices.xy, g_MaterialParamsOutput0, g_MaterialParamsOutput1);
			}

			camVertexContext.currentNodeForwardPDFMIS = pdfForwardCamera;
            float misWeight = calculateMISWeightOnCameraPathMissing(camVertexIndex, camVertexContext, rayOrigin, rayDir);
			
			float4 skyColor = getSkyBoxColor(rayDir, g_envType, g_envTexIndex);
			if(shouldPathContribute(camVertexIndex, 0))
			{
#ifdef WHITE_FURNACE_TEST
				totalLight = totalLight + camVertexContext.throughput * ToSpectralSamples(float3(1,1,1)) * misWeight;
#else
				totalLight = totalLight + camVertexContext.throughput * ToSpectralSamples(skyColor.xyz) * misWeight;
#endif
				++pathCount;
			}
			break;
		}
	}

	bool rayDispersed = (rayState.flags & RAYSTATE_FLAGS_SECONDARY_LAMBDAS_TERMINATED) != 0;
    float3 color = totalLight.ToRGB(COLORSPACE_DEFAULT, rayDispersed);

	color /= pathCount;

	g_outputColor[sourceTextureIndices.xy]  = float4(color, 1.f);
    
	/*
	if(camVertexIndex == 0)
	{
		g_outputColor[sourceTextureIndices.xy] = float4(1.0f, 0.0f, 0.0f,  1.f);
	} else if(camVertexIndex == 1)
	{
		g_outputColor[sourceTextureIndices.xy] = float4(0.0f, 1.0f, 0.0f, 1.f);
	} else if(camVertexIndex < 6)
	{
		g_outputColor[sourceTextureIndices.xy] = float4(0.0f, 0.0f, 1.0f,  10.f);
	} else if(camVertexIndex < 15)
	{
		g_outputColor[sourceTextureIndices.xy] = float4(1.0f, 0.0f, 1.0f,  20.f);
	}
	else 
	{
		g_outputColor[sourceTextureIndices.xy] = float4(1.0f, 1.0f, 1.0f,  1.f);
	}
	return;
	*/
	
	
	/*
	if(payload.numberVolumesEntered == 0 || payload.rayState == RAY_STATE_CANCELLED)
	{
		g_outputColor[sourceTextureIndices.xy] = float4(1.0f, 0.0f, 0.0f,  1.f);
	} else if(payload.numberVolumesEntered < 2)
	{
		g_outputColor[sourceTextureIndices.xy] = float4(0.0f, 1.0f, 0.0f, 1.f);
	} else
	{
		g_outputColor[sourceTextureIndices.xy] = float4(0.0f, 0.0f, 1.0f,  1.f);
	}
	return;
	*/
	
	/*
	bool resultsValid = !payload.totalLight.hasNan();
	//if the ray was terminated, write out results. if it was cancelled, don't add samples this frame
	if((payload.rayState == RAY_STATE_TERMINATED) && resultsValid) 
	{
		g_outputColor[sourceTextureIndices.xy] = color;
	} 
	else
	{
		g_outputColor[sourceTextureIndices.xy] = float4(0.0f, 0.0f, 0.0f, 0.0f);
		//g_outputColor[sourceTextureIndices.xy] = float4(10.0f, 0.0f, 0.0f, 10.0f); //flag killed samples visually
		//g_outputColor[sourceTextureIndices.xy] = float4(payload.totalLight, 10.0f); //flag killed samples visually
	}*/
}

#endif

