#include "BDPTCommon.hlsl"

RWByteAddressBuffer g_perTexelPureLightPathHeader : register(u5, space3);

[numthreads(THREAD_GROUP_DIM_SIZE_CAM_RAY, THREAD_GROUP_DIM_SIZE_CAM_RAY, 1)]
void initializePureLightPathResources( uint3 groupId : SV_GroupID,
    uint3 groupThreadId : SV_GroupThreadID,
    uint3 dispatchThreadId : SV_DispatchThreadID,
    uint groupIndex : SV_GroupIndex )
{
	if(dispatchThreadId.x >= g_targetTexDimensions.x || dispatchThreadId.y >= g_targetTexDimensions.y) return;
	uint offset = calculatePureLightPathHeaderOffset(dispatchThreadId.xy);
	g_perTexelPureLightPathHeader.Store2(offset, uint2(INVALID_PURE_LIGHT_NODE_INDEX, INVALID_PURE_LIGHT_NODE_INDEX));

}
