

#ifdef CAMERA_RAYS_STAGE
RWTexture2D<float4> g_outputColor : register(u5, space3);
#elif LIGHT_RAYS_STAGE
#define WRITABLE_LIGHT_DATA
#endif

static uint g_spectralSampleOffset;

#define RTCR_SPECTRAL_SAMPLESET_EXTRA_OFFSET g_spectralSampleOffset

#include "BDPTCommon.hlsl"

#ifdef CAMERA_RAYS_STAGE

[numthreads(8, 8, 1)]
void traceCameraRays( uint3 groupId : SV_GroupID,
    uint3 groupThreadId : SV_GroupThreadID,
    uint3 dispatchThreadId : SV_DispatchThreadID,
    uint groupIndex : SV_GroupIndex )
{

	g_spectralSampleOffset = (dispatchThreadId.y % 2) * 2 + (dispatchThreadId.x % 2);

	float2 uv = (float2)dispatchThreadId.xy * g_targetTexDimensions.zw;
    float3 rayDir = generateRayDirection(uv + g_rayDirUvOffset);
	float3 rayOrigin = g_cameraPosition;
	

	uint rayFlags = RAY_FLAG_NONE;//RAY_FLAG_CULL_FRONT_FACING_TRIANGLES; //RAY_FLAG_NONE; //RAY_FLAG_CULL_BACK_FACING_TRIANGLES
	uint InstanceInclusionMask = ~0;

	RayQuery<RAY_FLAG_NONE> q;

	RayDesc ray;
	ray.Origin = rayOrigin;
	ray.Direction = rayDir;
	ray.TMin = 0.0001f;
	ray.TMax = 1000.0;

	q.TraceRayInline(
        g_accelerationStructure,
        rayFlags, 
        InstanceInclusionMask,
        ray);

    while(q.Proceed());

	float4 color = 0;
    if(q.CommittedStatus() == COMMITTED_TRIANGLE_HIT)
    {
		uint instanceInd = q.CommittedInstanceID();
		uint primitiveIndex = q.CommittedPrimitiveIndex();
		float t = q.CommittedRayT();
		float2 barycentrics2 = q.CommittedTriangleBarycentrics();

		uint2 matMeshIndices = getMaterialAndMeshIndices(instanceInd);
		MeshEntryGPU meshEntry = getMeshEntry(matMeshIndices.y);


		//Initial surface setup
		float3 barycentrics = float3(1 - barycentrics2.x - barycentrics2.y, barycentrics2.x, barycentrics2.y);
		uint3 indices = fetchIndices(meshEntry.indexBuffer, primitiveIndex);
		float3 geometryNormal = fetchMeshNormal(meshEntry.normalBuffer, indices, barycentrics);
		float3 tangent = meshHasValidTangents(meshEntry.tangentBuffer) ? fetchMeshTangent(meshEntry.tangentBuffer, indices, barycentrics) : float3(1.f, 0.f, 0.f);
		float2 uv = meshHasValidUVs(meshEntry.uvBuffer) ? fetchMeshUV(meshEntry.uvBuffer, indices, barycentrics) : float2(0.5f, 0.5f);

		float3 normal = geometryNormal;

		//fetch surface material parameters
		MaterialEntryGPU matEntry = getMaterialEntry(matMeshIndices.x);
		SurfaceDefinitionRGB surfaceDefRGB;
		fetchSurfaceMaterialParameters(matEntry, surfaceDefRGB);
		modifySurfaceMaterialParametersWithTextures(matEntry, uv, normal, tangent, surfaceDefRGB);
		SurfaceDefinition surfaceDef = convertSurfaceDefinitionFromRGB(surfaceDefRGB);


		color.xyz = surfaceDef.albedo.ToRGB(COLORSPACE_DEFAULT, false);
		color.a = 1.f;
    }
    else 
    {
        color = float4(0, 0, 0, 1);
    }

	g_outputColor[dispatchThreadId.xy] = color;
    
	/*
	if(payload.pathLength == 1)
	{
		g_outputColor[dispatchThreadId.xy] = float4(1.0f, 0.0f, 0.0f,  1.f);
	} else if(payload.pathLength < 3)
	{
		g_outputColor[dispatchThreadId.xy] = float4(0.0f, 1.0f, 0.0f, 1.f);
	} else if(payload.pathLength < 6)
	{
		g_outputColor[dispatchThreadId.xy] = float4(0.0f, 0.0f, 1.0f,  10.f);
	} else if(payload.pathLength < 15)
	{
		g_outputColor[dispatchThreadId.xy] = float4(1.0f, 0.0f, 1.0f,  20.f);
	}
	else 
	{
		g_outputColor[dispatchThreadId.xy] = float4(1.0f, 1.0f, 1.0f,  1.f);
	}
	return;
	*/
	
	
	/*
	if(payload.numberVolumesEntered == 0 || payload.rayState == RAY_STATE_CANCELLED)
	{
		g_outputColor[dispatchThreadId.xy] = float4(1.0f, 0.0f, 0.0f,  1.f);
	} else if(payload.numberVolumesEntered < 2)
	{
		g_outputColor[dispatchThreadId.xy] = float4(0.0f, 1.0f, 0.0f, 1.f);
	} else
	{
		g_outputColor[dispatchThreadId.xy] = float4(0.0f, 0.0f, 1.0f,  1.f);
	}
	return;
	*/
	
	/*
	bool resultsValid = !payload.totalLight.hasNan();
	//if the ray was terminated, write out results. if it was cancelled, don't add samples this frame
	if((payload.rayState == RAY_STATE_TERMINATED) && resultsValid) 
	{
		g_outputColor[dispatchThreadId.xy] = color;
	} 
	else
	{
		g_outputColor[dispatchThreadId.xy] = float4(0.0f, 0.0f, 0.0f, 0.0f);
		//g_outputColor[dispatchThreadId.xy] = float4(10.0f, 0.0f, 0.0f, 10.0f); //flag killed samples visually
		//g_outputColor[dispatchThreadId.xy] = float4(payload.totalLight, 10.0f); //flag killed samples visually
	}
	*/
	

}

#endif

//#define LIGHT_RAYS_STAGE //DONT FORGET TO REMOVE/DISABLE
#ifdef LIGHT_RAYS_STAGE

[numthreads(64, 1, 1)]
void traceLightRays( uint3 groupId : SV_GroupID,
    uint3 groupThreadId : SV_GroupThreadID,
    uint3 dispatchThreadId : SV_DispatchThreadID,
    uint groupIndex : SV_GroupIndex )
{

	g_spectralSampleOffset = 0;

	uint sampleIndex = g_currentRandomSampleIndex + dispatchThreadId.y * g_lightPathsPerDim.x;

	SpectralSamples throughPut;
	float3 lightPos;
	float3 lightDir;
	float lightSamplePDF;

	//sample light
	{
		float4 randomSamples0 = getRandomSampleFloat4(sampleIndex, 0);
		float4 randomSamples1 = getRandomSampleFloat4(sampleIndex, 1);

		sampleLightOrEnv(randomSamples1.w, randomSamples0, 0.5f, throughPut, lightPos, lightDir, lightSamplePDF);
	}


	if(throughPut.allSamplesEqual(0.f)) return;

	BDPTRayState rayState;
	rayState.absorption.set(0);
    rayState.setStateFlags(0);
    rayState.numberVolumesEntered = 0;

    float pdfSumRatio = 1;
	
	for(uint i = 1; i < g_maxVerticesPerLightPath; ++i)
	{
		float4 randomSamples0 = getRandomSampleFloat4(sampleIndex + i, 0);

		uint rayFlags = RAY_FLAG_NONE;
		uint InstanceInclusionMask = ~0;

		RayQuery<RAY_FLAG_NONE> q;

		RayDesc ray;
		ray.Origin = lightPos;
		ray.Direction = lightDir;
		ray.TMin = 0.0001f;
		ray.TMax = 1000.0;

		q.TraceRayInline(
		    g_accelerationStructure,
		    rayFlags, 
		    InstanceInclusionMask,
		    ray);

		while(q.Proceed());

		if(q.CommittedStatus() == COMMITTED_TRIANGLE_HIT)
		{
			
            SurfaceDefinition surfaceDef;
            PrecalculatedSurfaceData precalculatedSurfaceData;
            float samplingProbabilities[LAYER_COUNT];
            bool triangleHitFrontFace = q.CommittedTriangleFrontFace();
            float3 woOS = -q.CommittedObjectRayDirection();
            uint instId = q.CommittedInstanceID();
            uint primIndex = q.CommittedPrimitiveIndex();
            float2 bary = q.CommittedTriangleBarycentrics();
			
			
            calculateCommonSurfaceParams(rayState, instId, primIndex, bary, woOS, triangleHitFrontFace, randomSamples0.xy,
            surfaceDef, precalculatedSurfaceData, samplingProbabilities);

            float3 wiOS = getSampleDirectionOS(surfaceDef, precalculatedSurfaceData, randomSamples0.w, randomSamples0.xy, samplingProbabilities);

            float3x3 transformNormal = (float3x3)q.CandidateWorldToObject3x4();
            transformNormal = transpose(transformNormal);
			
            float3 normalWS = mul(transformNormal, surfaceDef.geometryNormal);
            float3 posWS = q.WorldRayOrigin() + q.WorldRayDirection() * q.CommittedRayT();
			

            LightPathNode pathNode;
            pathNode.instancePrimitiveBarycentrics = float4(asfloat(q.CommittedInstanceID()), asfloat(q.CommittedInstanceID()), bary.x, bary.y);
            pathNode.normalWSPDF.xyz = normalWS;
            pathNode.throughput = throughPut.toFloat4();
            pathNode.positionWSMISSum = float4(posWS, pdfSumRatio);
			
            if (isZero(wiOS))
            {
                break;
            }
                
            SpectralSamples w;
            float pdfForward;
            float pdfBackward;
            evaluateSurfaceAndPDFs(surfaceDef, precalculatedSurfaceData, samplingProbabilities, rayState, woOS, wiOS, triangleHitFrontFace, w, pdfForward, pdfBackward);

            float areaMultiplier = areaDensityMultiplier(posWS - q.WorldRayOrigin(), normalWS);
			
            pdfForward *= areaMultiplier;
            pdfBackward *= areaMultiplier;
			
            pdfSumRatio *= pdfForward / pdfBackward;
            throughPut = throughPut * w;

        }
		else 
		{
		    //end path
		}


	}
	

}

#endif