#include <PyRendererBasicTypes.h>
#include <Gfx/GfxBasicTypes.h>
namespace YAPT
{
	DEFINE_BINDING_CLASS(PyRendererBasicTypes)

		
	BINDING_FUNC(PyRendererBasicTypes, m)
	{

        pybind11::enum_<ResourceDimension>(m, "ResourceDimension")
            .value("BUFFER", ResourceDimension::BUFFER)
            .value("TEXTURE_1D", ResourceDimension::TEXTURE_1D)
            .value("TEXTURE_1D_ARRAY", ResourceDimension::TEXTURE_1D_ARRAY)
            .value("TEXTURE_2D", ResourceDimension::TEXTURE_2D)
            .value("TEXTURE_2D_ARRAY", ResourceDimension::TEXTURE_2D_ARRAY)
            .value("TEXTURE_3D", ResourceDimension::TEXTURE_3D)
            .value("TEXTURE_CUBEMAP", ResourceDimension::TEXTURE_CUBEMAP)
            .value("TEXTURE_CUBEMAP_ARRAY", ResourceDimension::TEXTURE_CUBEMAP_ARRAY)
            .value("UNDEFINED", ResourceDimension::UNDEFINED);


        pybind11::enum_<ResourceFormat>(m, "ResourceFormat")
            .value("UNKNOWN", ResourceFormat::UNKNOWN)
            .value("R8_UNORM", ResourceFormat::R8_UNORM)
            .value("R8_SNORM", ResourceFormat::R8_SNORM)
            .value("R8_UINT", ResourceFormat::R8_UINT)
            .value("R8_SINT", ResourceFormat::R8_SINT)
            .value("R8_SRGB", ResourceFormat::R8_SRGB)
            .value("R16_UNORM", ResourceFormat::R16_UNORM)
            .value("R16_SNORM", ResourceFormat::R16_SNORM)
            .value("R16_UINT", ResourceFormat::R16_UINT)
            .value("R16_SINT", ResourceFormat::R16_SINT)
            .value("R16_SFLOAT", ResourceFormat::R16_SFLOAT)
            .value("R32_UINT", ResourceFormat::R32_UINT)
            .value("R32_SINT", ResourceFormat::R32_SINT)
            .value("R32_SFLOAT", ResourceFormat::R32_SFLOAT)
            .value("RG8_UNORM", ResourceFormat::RG8_UNORM)
            .value("RG8_SNORM", ResourceFormat::RG8_SNORM)
            .value("RG8_UINT", ResourceFormat::RG8_UINT)
            .value("RG8_SINT", ResourceFormat::RG8_SINT)
            .value("RG8_SRGB", ResourceFormat::RG8_SRGB)
            .value("RG16_UNORM", ResourceFormat::RG16_UNORM)
            .value("RG16_SNORM", ResourceFormat::RG16_SNORM)
            .value("RG16_UINT", ResourceFormat::RG16_UINT)
            .value("RG16_SINT", ResourceFormat::RG16_SINT)
            .value("RG16_SFLOAT", ResourceFormat::RG16_SFLOAT)
            .value("RG32_UINT", ResourceFormat::RG32_UINT)
            .value("RG32_SINT", ResourceFormat::RG32_SINT)
            .value("RG32_SFLOAT", ResourceFormat::RG32_SFLOAT)
            .value("RGB8_UNORM", ResourceFormat::RGB8_UNORM)
            .value("RGB8_SNORM", ResourceFormat::RGB8_SNORM)
            .value("RGB8_UINT", ResourceFormat::RGB8_UINT)
            .value("RGB8_SINT", ResourceFormat::RGB8_SINT)
            .value("RGB8_SRGB", ResourceFormat::RGB8_SRGB)
            .value("BGR8_UNORM", ResourceFormat::BGR8_UNORM)
            .value("BGR8_SNORM", ResourceFormat::BGR8_SNORM)
            .value("BGR8_UINT", ResourceFormat::BGR8_UINT)
            .value("BGR8_SINT", ResourceFormat::BGR8_SINT)
            .value("BGR8_SRGB", ResourceFormat::BGR8_SRGB)
            .value("RGB32_UINT", ResourceFormat::RGB32_UINT)
            .value("RGB32_SINT", ResourceFormat::RGB32_SINT)
            .value("RGB32_SFLOAT", ResourceFormat::RGB32_SFLOAT)
            .value("RGBA8_UNORM", ResourceFormat::RGBA8_UNORM)
            .value("RGBA8_SNORM", ResourceFormat::RGBA8_SNORM)
            .value("RGBA8_UINT", ResourceFormat::RGBA8_UINT)
            .value("RGBA8_SINT", ResourceFormat::RGBA8_SINT)
            .value("RGBA8_SRGB", ResourceFormat::RGBA8_SRGB)
            .value("BGRA8_UNORM", ResourceFormat::BGRA8_UNORM)
            .value("BGRA8_SNORM", ResourceFormat::BGRA8_SNORM)
            .value("BGRA8_UINT", ResourceFormat::BGRA8_UINT)
            .value("BGRA8_SINT", ResourceFormat::BGRA8_SINT)
            .value("BGRA8_SRGB", ResourceFormat::BGRA8_SRGB)
            .value("RGBA16_UNORM", ResourceFormat::RGBA16_UNORM)
            .value("RGBA16_SNORM", ResourceFormat::RGBA16_SNORM)
            .value("RGBA16_UINT", ResourceFormat::RGBA16_UINT)
            .value("RGBA16_SINT", ResourceFormat::RGBA16_SINT)
            .value("RGBA16_SFLOAT", ResourceFormat::RGBA16_SFLOAT)
            .value("RGBA32_UINT", ResourceFormat::RGBA32_UINT)
            .value("RGBA32_SINT", ResourceFormat::RGBA32_SINT)
            .value("RGBA32_SFLOAT", ResourceFormat::RGBA32_SFLOAT)
            .value("D16_UNORM", ResourceFormat::D16_UNORM)
            .value("D32_SFLOAT", ResourceFormat::D32_SFLOAT)
            .value("D24_UNORM_S8_UINT", ResourceFormat::D24_UNORM_S8_UINT)
            .value("BC4_UNORM", ResourceFormat::BC4_UNORM)
            .value("BC4_SNORM", ResourceFormat::BC4_SNORM)
            .value("BC6H_SFLOAT", ResourceFormat::BC6H_SFLOAT)
            .value("BC6H_UFLOAT", ResourceFormat::BC6H_UFLOAT)
            .value("BC7_UNORM", ResourceFormat::BC7_UNORM)
            .value("BC7_UNORM_SRGB", ResourceFormat::BC7_UNORM_SRGB);


        pybind11::enum_<ResourceUsageBits>(m, "ResourceUsageBits")
            .value("UNKNOWN", RESOURCE_USAGE_UNKNOWN)
            .value("COPY_DESTINATION", RESOURCE_USAGE_COPY_DESTINATION)
            .value("COPY_SOURCE", RESOURCE_USAGE_COPY_SOURCE)
            .value("UNIFORM_BUFFER", RESOURCE_USAGE_UNIFORM_BUFFER)
            .value("UNIFORM_TEXEL_BUFFER", RESOURCE_USAGE_UNIFORM_TEXEL_BUFFER)
            .value("STORAGE_BUFFER", RESOURCE_USAGE_STORAGE_BUFFER)
            .value("STORAGE_TEXEL_BUFFER", RESOURCE_USAGE_STORAGE_TEXEL_BUFFER)
            .value("VERTEX_BUFFER", RESOURCE_USAGE_VERTEX_BUFFER)
            .value("INDEX_BUFFER", RESOURCE_USAGE_INDEX_BUFFER)
            .value("SHADERTABLE_BUFFER", RESOURCE_USAGE_SHADERTABLE_BUFFER)
            .value("ACCELERATION_STRUCTURE_BUFFER", RESOURCE_USAGE_ACCELERATION_STRUCTURE_BUFFER)
            .value("ACCELERATION_STRUCTURE_BUILD_INPUT", RESOURCE_USAGE_ACCELERATION_STRUCTURE_BUILD_INPUT)
            .value("SAMPLED_TEXTURE", RESOURCE_USAGE_SAMPLED_TEXTURE)
            .value("STORAGE_TEXTURE", RESOURCE_USAGE_STORAGE_TEXTURE)
            .value("RENDER_TARGET_TEXTURE", RESOURCE_USAGE_RENDER_TARGET_TEXTURE)
            .value("DEPTH_TEXTURE", RESOURCE_USAGE_DEPTH_TEXTURE)
            .value("STENCIL_TEXTURE", RESOURCE_USAGE_STENCIL_TEXTURE)
            .value("PRESENTABLE_TEXTURE", RESOURCE_USAGE_PRESENTABLE_TEXTURE)
            .value("DEPTH_STENCIL_TEXTURE", RESOURCE_USAGE_DEPTH_STENCIL_TEXTURE)
            .export_values();
	}
}