#pragma once

#include <Renderer/Shared/CRendererConfiguration.h>
#include <Renderer/Shared/CRenderer.h>

#define INIT_LIST(...) {__VA_ARGS__}

#define INIT_RENDERVARSLIST_TEXTURE(NAME) config->registerVariable(NAME, new CRendererVariableResource<Texture, RenderVariableTextureInternal, RendererVariableType::TEXTURE>(*config));
#define INIT_RENDERVARSLIST_BUFFER(NAME) config->registerVariable(NAME,  new CRendererVariableResource<Buffer, RenderVariableBufferInternal, RendererVariableType::BUFFER>(*config));

#define INIT_RENDERVARSLIST_INT(NAME, DEFAULT, MIN, MAX) config->registerVariable(NAME, constructNumericRenderVar<RenderVariableIntInternal, RendererVariableType::INT>(*config, DEFAULT, MIN, MAX));
#define INIT_RENDERVARSLIST_FLOAT(NAME, DEFAULT, MIN, MAX) config->registerVariable(NAME, constructNumericRenderVar<RenderVariableFloatInternal, RendererVariableType::FLOAT>(*config, DEFAULT, MIN, MAX));

#define INIT_RENDERVARSLIST_OPTIONS(NAME, SELECTED, OPTIONS) {const char* optionsList[] = INIT_LIST OPTIONS; config->registerVariable(NAME, new CRendererVariableOptions<sizeof(optionsList)/sizeof(char*)>(*config, SELECTED, optionsList));}

namespace YAPT
{
	inline void initRVars(CRendererConfiguration* config)
	{
		//general
		INIT_RENDERVARSLIST_TEXTURE(RVARNAME_SKYBOX);
		INIT_RENDERVARSLIST_FLOAT(RVARNAME_ENV_INTENSITY_SCALE, 1.f, 0.f, 100000.f);
		INIT_RENDERVARSLIST_INT(RVARNAME_RENDER_RESOLUTION, ivec2p(1920, 1080), ivec2p(2, 2), ivec2p(99999999, 99999999));
		INIT_RENDERVARSLIST_OPTIONS(RVARNAME_ACTIVE_RENDERPIPELINE, 0, ("BPT", "BPT_WITH_NEE", "BDPT", "DBG_Normals", "DBG_Tangents", "DBG_UV"))
		INIT_RENDERVARSLIST_OPTIONS(RVARNAME_DENOISE_MODE, 0, ("OFF", "ON", "DEBUG_MAT_PARAMS", "DEBUG_VARIANCE", "DEBUG_SHOW_SAMPLE_SOURCES"))
		INIT_RENDERVARSLIST_FLOAT(RVARNAME_DENOISE_DEPTH_SIGMA_SCALE, 0.02f, 0.00001f, 10.f)
		INIT_RENDERVARSLIST_FLOAT(RVARNAME_DENOISE_NORMAL_SIGMA, 0.002f, 0.00001f, 1000.f)
		INIT_RENDERVARSLIST_FLOAT(RVARNAME_DENOISE_MATERIAL_DIFFERENCE_SIGMA, 0.02f, 0.00001f, 1000.f)
		INIT_RENDERVARSLIST_FLOAT(RVARNAME_DENOISE_COLOR_DIFFERENCE_SIGMA, 3.f, 0.00001f, 1000.f)

		//path regularization / firefly control
		INIT_RENDERVARSLIST_INT(RVARNAME_REGULARIZE_AFTER_VERTICES, 8, 0, 64);
		INIT_RENDERVARSLIST_FLOAT(RVARNAME_FIREFLY_CLAMP_SCALE, 12.f, 0.f, 100000.f);
		INIT_RENDERVARSLIST_FLOAT(RVARNAME_FIREFLY_CLAMP_RELAX_POWER, 0.5f, 0.f, 4.f);
		INIT_RENDERVARSLIST_OPTIONS(RVARNAME_KILL_NAN_SAMPLES, 1, ("OFF", "ON"));


		//Debug
		INIT_RENDERVARSLIST_INT(RVARNAME_DEBUG_BDPT_LIGHTPATHNODES, ivec2p(0, 128), ivec2p(0, 0), ivec2p(99999999, 99999999));
		INIT_RENDERVARSLIST_INT(RVARNAME_DEBUG_BDPT_CAMERAPATHNODES, ivec2p(0, 128), ivec2p(0, 0), ivec2p(99999999, 99999999));

		//Tonemap
		INIT_RENDERVARSLIST_OPTIONS(RVARNAME_TONEMAP_ENABLE, 1, ("OFF", "ON"));
		INIT_RENDERVARSLIST_FLOAT(RVARNAME_TONEMAP_TOE, 1.f, 0.f, 100.f);
		INIT_RENDERVARSLIST_FLOAT(RVARNAME_TONEMAP_MID, 1.f, 0.f, 100.f);
		INIT_RENDERVARSLIST_FLOAT(RVARNAME_TONEMAP_SHOULDER, 1.f, 0.f, 100.f);
		INIT_RENDERVARSLIST_OPTIONS(RVARNAME_TONEMAP_USE_AUTOEXPOSURE, 1 , ("OFF", "ON"));
		INIT_RENDERVARSLIST_FLOAT(RVARNAME_TONEMAP_EXPOSURE_COMPENSATION, 0.f, -10000.f, 10000.f);
		INIT_RENDERVARSLIST_FLOAT(RVARNAME_TONEMAP_EYE_ADAPT_SPEED, 1.f, 0.f, 1000.f);
		INIT_RENDERVARSLIST_FLOAT(RVARNAME_TONEMAP_MANUALEXPOSURE, 1.f, 0.f, 9999999999999999.f);

		config->commitChanges();
	}

}