#include "../globalDefinitions.hlsl"

struct ClearAccumulatedSamplesParams
{
	uint4 targetTextureDimensions;
	float4 clearValue;
    uint accumulationTargetCount;
};


ConstantBuffer<ClearAccumulatedSamplesParams> g_mergeParams : register(b0, space0);
RWTexture2DArray<float4> g_targetTex : register(u1, space0);
RWTexture2D<uint> g_sampleCountsTex : register(u2, space0);


[numthreads(8, 8, 1)]
void main( uint3 groupId : SV_GroupID,
    uint3 groupThreadId : SV_GroupThreadID,
    uint3 dispatchThreadId : SV_DispatchThreadID,
    uint groupIndex : SV_GroupIndex )
{
	if(dispatchThreadId.x < g_mergeParams.targetTextureDimensions.x && dispatchThreadId.y < g_mergeParams.targetTextureDimensions.y)
	{
        for (uint i = 0; i < g_mergeParams.accumulationTargetCount; ++i)
        {
            uint3 texCoord = uint3(dispatchThreadId.x, dispatchThreadId.y, i);
            g_targetTex[texCoord] = g_mergeParams.clearValue;
        }
            
        g_sampleCountsTex[dispatchThreadId.xy] = 0;
    }
}

