#include "../globalDefinitions.hlsl"
#include "../common/common.hlsl"
#include "../common/commonMath.hlsl"
#include "materialParameterTextures.hlsl"

struct DenoiseParams
{
    float4x4 uvToView;
    float4x4 viewToWorld;
    float4 cameraPosition;
    float4 textureDimensions;
    uint4 modePassIndex;
    float4 bilaterWeightParams;
};



#define DENOISE_MODE_OFF 0
#define DENOISE_MODE_ON 1
#define DENOISE_MODE_MAT_PARAMS_DEBUG 2
#define DENOISE_MODE_VARIANCE_DEBUG 3
#define DENOISE_SHOW_SAMPLE_SOURCES 4

ConstantBuffer<DenoiseParams> g_denoiseParams : register(b0, space0);
Texture2D g_sourceTex : register(t1, space0);
Texture2D<uint4> g_materialParams0 : register(t2, space0);
Texture2D<uint4> g_materialParams1 : register(t3, space0);
Texture2D<float> g_varianceTex : register(t4, space0);
Texture2D g_lastSamples : register(t5, space0);
RWTexture2D<float4> g_denoiseColor : register(u6, space0);
RWTexture2D<float4> g_denoiseVariance : register(u7, space0);

#define g_denoiseMode (g_denoiseParams.modePassIndex.x)
#define g_denoisePassIndex (g_denoiseParams.modePassIndex.y)
#define g_denoiseTextureSize (g_denoiseParams.textureDimensions.xy)
#define g_denoiseTextureSizeInv (g_denoiseParams.textureDimensions.zw)
#define g_denoiseDepthSigmaScale (g_denoiseParams.bilaterWeightParams.x)
#define g_denoiseNormalSigma (g_denoiseParams.bilaterWeightParams.y)
#define g_denoiseMaterialSigma (g_denoiseParams.bilaterWeightParams.z)

float4 calculateDebugMaterialParams(uint2 loc)
{
    float2 scaledUv = (loc * g_denoiseParams.textureDimensions.zw) * 2.f;
    uint2 readLocation = frac(scaledUv) * g_denoiseParams.textureDimensions.xy;
    
    MaterialParameters2Texture matParams = readMaterialParametersFromTextures(readLocation, g_materialParams0, g_materialParams1);
    
    if(scaledUv.x < 1)
    {
        if (scaledUv.y < 1)
        {
            return float4(matParams.albedo, 1);
        } 
        else
        {
            return float4(matParams.normal * 0.5f + 0.5f, 1);
        }
    } 
    else
    {
        if (scaledUv.y < 1)
        {
            return float4(matParams.anisotropy, matParams.ior, matParams.roughness, 1.f);
        }
        else
        {
            return float4(matParams.metalness, matParams.depth, matParams.transparency, 1.f);
        }
    }
}


float calculateVisualDifferenceAlbedo(float3 a, float3 b)
{
    float3 delta = saturate(abs(a - b));
    return (delta.x + delta.y + delta.z) * 0.3333f;

}

float calculatePerceptualLuminance(float3 c)
{
    return dot(c, float3(0.2126, 0.7152, 0.0722));
}

float calculateMaterialParamsDiffWeight(MaterialParameters2Texture a, MaterialParameters2Texture b, float normalDeltaSigma, float matDeltaSigma)
{
    float roughnessDelta = abs(a.roughness - b.roughness);
    float albedoDelta = calculateVisualDifferenceAlbedo(a.albedo, b.albedo);
    float anisoDiff = abs(a.anisotropy - b.anisotropy);
    float normalDot = saturate(dot(a.normal, b.normal));
    float iorDelta = abs(a.ior - b.ior);
    float metalnessDelta = abs(a.metalness - b.metalness);
    float transparencyDelta = abs(a.transparency - b.transparency);

    //TODO: flags and better weight calculation: this multiplicative weight is likely too aggressive
    float wMat = 1.f;
    wMat *= saturate(1.f - roughnessDelta);
    wMat *= saturate(1.f - albedoDelta);
    wMat *= saturate(1.f - anisoDiff);
    wMat *= saturate(0.5f + 0.5f * (1.f - saturate(iorDelta))); //lessen effect of ior
    wMat *= saturate(1.f - metalnessDelta);
    wMat *= saturate(1.f - transparencyDelta);
    
    float wNormal = normalDot;
    
    
    wMat = exp((-1.f + wMat) / max(matDeltaSigma, 1e-6));
    wNormal = exp((-1.f + wNormal) / max(normalDeltaSigma, 1e-6));
    
    return wNormal * wMat;
}



float3 reconstructWorldPosition(uint2 loc, float depth)
{
    float2 uv = (float2(loc) + 0.5f) * g_denoiseParams.textureDimensions.zw;

    float4 pointOnNearPlane = float4(uv, 0.0f, 1.0f);
    pointOnNearPlane = mul(g_denoiseParams.uvToView, pointOnNearPlane);
    pointOnNearPlane /= pointOnNearPlane.w;
    pointOnNearPlane.w = 0;

    float3 rayDir = normalize(mul(g_denoiseParams.viewToWorld, pointOnNearPlane).xyz);
    return g_denoiseParams.cameraPosition.xyz + rayDir * depth;
}

float calculatePlaneDistanceWeight(float3 centerPos, float3 centerNormal, float3 samplePos, float sigma)
{
    float planeDist = abs(dot(centerNormal, samplePos - centerPos));
    return exp(-planeDist / max(sigma, 1e-4f));
}

float calculateKernelDistanceWeight(float2 deltaFromCenter, float sigma)
{
    return gaussian(deltaFromCenter, sigma);
}

uint floatToUint(float v)
{
    return uint(floor(max(v, 0) + 0.5f));
}

struct AtrousPassOutput
{
    float4 color;
    float variance;
};

AtrousPassOutput denoiseAtrous(int2 texCoord, uint passNumber)
{
    
    const float precalculatedGaussian3tap[3] = { 3.0 / 8.0, 1.0 / 4.0, 1.0 / 16.0 };

    const float precalculatedGaussian3x3tap[3][3] =
    {
        { 1.0 / 16, 1.0 / 8, 1.0 / 16 },
        { 1.0 / 8, 1.0 / 4, 1.0 / 8 },
        { 1.0 / 16, 1.0 / 8, 1.0 / 16 }
    };

    const float EPS_MIN = 1e-6;
    
    float filteredVarSum = 0.0;
    float filteredVarWeight = 0.0;

    for (int y = -1; y <= 1; y++)
    {
        for (int x = -1; x <= 1; x++)
        {
            int2 sampleLoc = int2(texCoord) + int2(x, y);
            
            if (sampleLoc.x < 0 || sampleLoc.x > (g_denoiseTextureSize.x - 1) || sampleLoc.y < 0 || sampleLoc.y > (g_denoiseTextureSize.y - 1))
                continue;
            
            float v = g_varianceTex.Load(uint3(sampleLoc.x, sampleLoc.y, 0));
            float w = precalculatedGaussian3x3tap[x + 1][y + 1];
            filteredVarSum    += v * w;
            filteredVarWeight += w;
        }
    }
    float centerVarFiltered = filteredVarSum / max(filteredVarWeight, EPS_MIN);
    float centerStdDev = sqrt(max(centerVarFiltered, EPS_MIN));

    MaterialParameters2Texture centerMatParams = readMaterialParametersFromTextures(texCoord.xy, g_materialParams0, g_materialParams1);
    float4 centercolor = g_sourceTex.Load(uint3(texCoord.xy, 0));
    float3 centerPos = reconstructWorldPosition(texCoord.xy, centerMatParams.depth);
    
    float4 sumColor = float4(0, 0, 0, 0);
    float  sumVarSq = 0.0;
    float  sumWeight = 0.0;

    float depthDistanceSigma = max(centerMatParams.depth * g_denoiseDepthSigmaScale, 0.001f);
    
    float materialDeltaWeight = 0.f;
    float materialDeltaPow = 1.f;
    float luminanceDeltaPow = 1.f;
    
    int stepSize = 1u << passNumber;

    for (int y = -2; y <= 2; y++)
    {
        for (int x = -2; x <= 2; x++)
        {
            int2 sampleLoc = int2(texCoord) + int2(x, y) * stepSize;

            if (sampleLoc.x < 0 || sampleLoc.x > (g_denoiseTextureSize.x - 1) || sampleLoc.y < 0 || sampleLoc.y > (g_denoiseTextureSize.y - 1))
                continue;
            
            float kernelWeight = precalculatedGaussian3tap[abs(x)] * precalculatedGaussian3tap[abs(y)];
            MaterialParameters2Texture matParams = readMaterialParametersFromTextures(sampleLoc, g_materialParams0, g_materialParams1);

            float4 sampleColor = g_sourceTex.Load(uint3(sampleLoc.x, sampleLoc.y, 0));
            float sampleVar = g_varianceTex.Load(uint3(sampleLoc.x, sampleLoc.y, 0));

            float3 samplePos = reconstructWorldPosition(sampleLoc, matParams.depth);
            float wDepth = calculatePlaneDistanceWeight(centerPos, centerMatParams.normal, samplePos, depthDistanceSigma);
            float wMat = calculateMaterialParamsDiffWeight(centerMatParams, matParams, g_denoiseNormalSigma, g_denoiseMaterialSigma);

            float colorDiff = abs(calculatePerceptualLuminance(sampleColor.rgb) - calculatePerceptualLuminance(centercolor.rgb));
            float wColor = exp(-colorDiff / (luminanceDeltaPow * centerStdDev + EPS_MIN));

            float w = kernelWeight * wDepth * wMat * wColor;

            sumColor  += sampleColor * w;
            sumVarSq  += w * w * sampleVar;
            sumWeight += w;
        }
    }

    float invWeight = 1.0 / max(sumWeight, EPS_MIN);

    AtrousPassOutput output;
    
    output.color = sumColor * invWeight;
    output.variance = sumVarSq * invWeight * invWeight;

    return output;
}


[numthreads(8, 8, 1)]
void main( uint3 groupId : SV_GroupID,
    uint3 groupThreadId : SV_GroupThreadID,
    uint3 dispatchThreadId : SV_DispatchThreadID,
    uint groupIndex : SV_GroupIndex )
{
    if (dispatchThreadId.x < g_denoiseTextureSize.x && dispatchThreadId.y < g_denoiseTextureSize.y)
	{
        float4 col = 0;
        if (g_denoiseMode == DENOISE_MODE_ON)
        {
            AtrousPassOutput o = denoiseAtrous(dispatchThreadId.xy, g_denoisePassIndex);
            col = o.color;
            g_denoiseVariance[dispatchThreadId.xy] = o.variance;

        }
        else if (g_denoiseMode == DENOISE_MODE_OFF)
        {
            col = g_sourceTex.Load(uint3(dispatchThreadId.xy, 0));
        }
        else if (g_denoiseMode == DENOISE_MODE_MAT_PARAMS_DEBUG)
        {
            col = calculateDebugMaterialParams(dispatchThreadId.xy);
        }
        else if (g_denoiseMode == DENOISE_MODE_VARIANCE_DEBUG)
        {
            float var = g_varianceTex.Load(uint3(dispatchThreadId.xy, 0));
            col = var;

        }
        else if (g_denoiseMode == DENOISE_SHOW_SAMPLE_SOURCES)
        {
            col = g_lastSamples.Load(uint3(dispatchThreadId.xy, 0)); //TODO
        }
        
        g_denoiseColor[dispatchThreadId.xy] = col;
        
		
		
	}
}

