#include "../globalDefinitions.hlsl"
#include "../common/common.hlsl"

struct DenoiseParams
{
    uint2 textureDimensions;
};


ConstantBuffer<DenoiseParams> g_denoiseParams : register(b0, space0);
Texture2D g_sourceTex : register(t1, space0);
Texture2D g_materialParams0 : register(t2, space0);
Texture2D g_materialParams1 : register(t3, space0);
RWTexture2D<float4> g_targetTex : register(u4, space0);

[numthreads(8, 8, 1)]
void main( uint3 groupId : SV_GroupID,
    uint3 groupThreadId : SV_GroupThreadID,
    uint3 dispatchThreadId : SV_DispatchThreadID,
    uint groupIndex : SV_GroupIndex )
{
    if (dispatchThreadId.x < g_denoiseParams.textureDimensions.x && dispatchThreadId.y < g_denoiseParams.textureDimensions.y)
	{
		float4 srcColor = g_sourceTex.Load(uint3(dispatchThreadId.xy, 0));
        g_targetTex[dispatchThreadId.xy] = srcColor;
		
	}
}

