#include "../globalDefinitions.hlsl"
#include "../common/common.hlsl"

struct MergeNewSamplesParams
{
	uint4 targetTextureOffsetScaleBias;
    uint4 randomSequence;
	uint2 targetTextureDimensions;
	uint2 sourceTextureDimensions;
	uint64_t sampleCount;
	
};

ConstantBuffer<MergeNewSamplesParams> g_mergeParams : register(b0, space0);
Texture2D g_sourceTex : register(t1, space0);
RWTexture2D<float4> g_targetTex : register(u2, space0);

#define GET_RANDOM_NUMBER_SEQUENCE_1(dimOffset) (g_mergeParams.randomSequence.x)
#define GET_RANDOM_NUMBER_SEQUENCE_2(dimOffset) (g_mergeParams.randomSequence.xy)
#define GET_RANDOM_NUMBER_SEQUENCE_3(dimOffset) (g_mergeParams.randomSequence.xyz)
#define GET_RANDOM_NUMBER_SEQUENCE_4(dimOffset) (g_mergeParams.randomSequence.xyxw)
#include "../common/randomSampler.hlsl"

//#define USE_PER_PIXEL_SAMPLE_COUNT
//#define NEAREST_SAMPLE_MERGE



void calculateSampleContribution(uint2 targetPos, out float4 colorOut, out float weightOut)
{
#ifdef NEAREST_SAMPLE_MERGE
	//TODO
    uint2 samplePos = g_mergeParams.targetTextureOffsetScaleBias.zw + targetPos / g_mergeParams.targetTextureOffsetScaleBias.xy;
    weightOut = 1;
    if (all(samplePos == targetPos))
    {
        colorOut = g_sourceTex[samplePos];
    } 
	else
    {
        colorOut = 0;
    }
#else

	//need random here, TODO
    float4 colorSum = 0;
	float2 toSrcTexMult = float2(1.f, 1.f) / g_mergeParams.targetTextureOffsetScaleBias.xy;
    float2 center = targetPos.xy + 0.5f;
    for (float x = max(targetPos.x - 1, 0) + g_mergeParams.targetTextureOffsetScaleBias.z; x < min(targetPos.x + 1, g_mergeParams.targetTextureDimensions.x - 1); x += g_mergeParams.targetTextureOffsetScaleBias.x)
    {
        for (float y = max(targetPos.y - 1, 0) + g_mergeParams.targetTextureOffsetScaleBias.w; y < min(targetPos.y + 1, g_mergeParams.targetTextureDimensions.y - 1); y += g_mergeParams.targetTextureOffsetScaleBias.y)
        {
            RandomSampler rand;
            rand.init(0, y * g_mergeParams.targetTextureDimensions.x + x);
            float2 samplePosFullres = float2(x, y) + rand.getTexelOffset();
            float2 d = abs(samplePosFullres - center);
            float2 weights = saturate(float2(1.f, 1.f) - d);
            float weight = weights.x * weights.y;
			if(weight > 0)
            {
                uint2 samplePos  = (uint2)floor(float2(x, y) * toSrcTexMult);
                float4 color = g_sourceTex[samplePos];
                colorSum += color * weight;
            }
			
			
        }
    }
    colorOut = colorSum;
#endif
    
	
	
}

[numthreads(8, 8, 1)]
void main( uint3 groupId : SV_GroupID,
    uint3 groupThreadId : SV_GroupThreadID,
    uint3 dispatchThreadId : SV_DispatchThreadID,
    uint groupIndex : SV_GroupIndex )
{
    if (dispatchThreadId.x < g_mergeParams.targetTextureDimensions.x && dispatchThreadId.y < g_mergeParams.targetTextureDimensions.y)
	{
        uint2 targetPosition = dispatchThreadId.xy;
        float4 srcColor;
        float weight;
		calculateSampleContribution(targetPosition, srcColor, weight);
		
		float4 dstColor = g_targetTex[targetPosition];
#ifdef USE_PER_PIXEL_SAMPLE_COUNT
		float w = dstColor.a + srcColor.a;
		if(w > 0)
		{
			float destBlend = dstColor.a / w;
			float srcBlend = srcColor.a / w;
			
			float4 output = float4(dstColor.xyz * destBlend + srcBlend * srcColor.xyz, w);
			g_targetTex[targetPosition] = output;
		}
#else
		if(srcColor.a > 0)
		{
			double w = 1.0/double(g_mergeParams.sampleCount);
			//TODO: keep everything 64 bit and have the target format match?
			float srcBlend = float(w);
			float destBlend = float(1 - w);
			
			float4 output = float4(dstColor.xyz * destBlend + srcBlend * srcColor.xyz, dstColor.w + 1);
			g_targetTex[targetPosition] = output;
		}
#endif
		
	}
}

